### ISSUE TITLE
Process hangs and got killed

### ISSUE THREAD

**Issue by visanuwan** [fenderglass/ABruijn#399] opened 2021-06-21 18:33 UTC
Dear Flye developer,

I used the latest version of Flye (2.8.3-b1695) to assemble ONT reads for short regions of the human genome with a size of around 50k-200kbp. However, I got a problem with some sets: hang (using all cores with 100%) or got killed by <Signals.SIGFPE: 8>.

Here is the error log from the hanging process. I killed it after letting it ran for a couple of days.
data: [https://app.box.com/s/hqw0q9jatdvdkgbaodn7odi4qcokcfov](url)
command: `flye --nano-raw assembly_hang.fa --threads 30 --out-dir output`
log:
```
[2021-06-13 21:35:59] DEBUG:    min_read_cov_cutoff=3
[2021-06-13 21:35:59] DEBUG:    short_tip_length=20000
[2021-06-13 21:35:59] DEBUG:    long_tip_length=100000
[2021-06-13 21:35:59] DEBUG: Running with k-mer size: 17
[2021-06-13 21:35:59] DEBUG: Running with minimum overlap 3000
[2021-06-13 21:35:59] DEBUG: Metagenome mode: Y
[2021-06-13 21:35:59] INFO: Reading sequences
[2021-06-13 21:36:00] DEBUG: Building positional index
[2021-06-13 21:36:00] DEBUG: Total sequence: 33673571 bp
[2021-06-13 21:36:02] INFO: Counting k-mers:
[2021-06-13 21:36:03] DEBUG: Updating k-mer histogram
[2021-06-13 21:36:55] DEBUG: Hash size: 50388
[2021-06-13 21:36:55] DEBUG: Total k-mers 1365291
[2021-06-13 21:36:55] INFO: Filling index table (1/2)
[2021-06-13 21:36:55] DEBUG: Mean k-mer frequency: 1237.61
[2021-06-13 21:36:55] DEBUG: Repetitive k-mer frequency: 123761
[2021-06-13 21:36:55] DEBUG: Filtered 0 repetitive k-mers (0)
[2021-06-13 21:36:55] INFO: Filling index table (2/2)
[2021-06-13 21:36:57] DEBUG: Sorting k-mer index
[2021-06-13 21:36:57] DEBUG: Selected k-mers: 13322
[2021-06-13 21:36:57] DEBUG: Index size: 13435501
[2021-06-13 21:36:57] DEBUG: Mean k-mer index frequency: 1008.52
[2021-06-13 21:36:57] DEBUG: Peak RAM usage: 8 Gb
[2021-06-13 21:36:57] DEBUG: Estimating k-mer identity bias
```
Here is the error log from the process with a kill signal
data: [https://app.box.com/s/wgw7fo718cunzgy0c1qpdhc45usan03d](url)
command: `flye --nano-raw assembly_error.fa --threads 30 --out-dir output`
log:
```
[2021-06-13 22:38:26] DEBUG:    min_read_cov_cutoff=3
[2021-06-13 22:38:26] DEBUG:    short_tip_length=20000
[2021-06-13 22:38:26] DEBUG:    long_tip_length=100000
[2021-06-13 22:38:26] DEBUG: Running with k-mer size: 17
[2021-06-13 22:38:26] DEBUG: Running with minimum overlap 1000
[2021-06-13 22:38:26] DEBUG: Metagenome mode: Y
[2021-06-13 22:38:26] INFO: Reading sequences
[2021-06-13 22:38:26] DEBUG: Building positional index
[2021-06-13 22:38:29] INFO: Counting k-mers:
[2021-06-13 22:38:29] DEBUG: Updating k-mer histogram
[2021-06-13 22:39:21] DEBUG: Hash size: 0
[2021-06-13 22:39:21] DEBUG: Total k-mers 0
[2021-06-13 22:39:21] INFO: Filling index table (1/2)
[2021-06-13 22:39:21] DEBUG: Mean k-mer frequency: 0
[2021-06-13 22:39:21] DEBUG: Repetitive k-mer frequency: 0
[2021-06-13 22:39:21] DEBUG: Filtered 0 repetitive k-mers (-nan)
[2021-06-13 22:39:21] INFO: Filling index table (2/2)
[2021-06-13 22:39:21] DEBUG: Sorting k-mer index
[2021-06-13 22:39:21] DEBUG: Selected k-mers: 0
[2021-06-13 22:39:21] DEBUG: Index size: 0
[2021-06-13 22:39:21] DEBUG: Mean k-mer index frequency: -nan
[2021-06-13 22:39:21] DEBUG: Peak RAM usage: 8 Gb
[2021-06-13 22:39:21] DEBUG: Estimating k-mer identity bias
[2021-06-13 22:39:21] root: ERROR: died with <Signals.SIGFPE: 8>.
[2021-06-13 22:39:21] root: ERROR: Pipeline aborted
```

Could you please help check on it?
I've tried it on different machines and it's reproducible.

Thanks!

**Comment by mikolmogorov** [comment] 2021-06-23 17:18
Hi,

Could you please post `flye.log` file?

**Comment by visanuwan** [comment] 2021-06-23 17:44
@fenderglass Please find `assembly_error_flye.log` and `assembly_hang_flye.log` in the attachment
[assembly_error_flye.log](https://github.com/fenderglass/Flye/files/6703911/assembly_error_flye.log)
[assembly_hang_flye.log](https://github.com/fenderglass/Flye/files/6703914/assembly_hang_flye.log)

**Comment by mikolmogorov** [comment] 2021-06-25 23:24
Thanks for sending the reports. In the SIGFPE case you did not have any reads above minimum overlap threshold (1kb), which caused unexpected behavior. This has been fixed in the latest github version.

In the case that did not finish - looks like you are trying to reassemble highly repetitive regions. Flye relies on a k-mer distribution within the whole genome, and in case of local assembly k-mer selection filters fail (that prevent highly repetitive k-mers to be used).  I'd suggest to assemble the entire genome (if you have reads) instead.

**Closed as completed by mikolmogorov** 2021-06-25 23:24 UTC
Labels: wontfix
