### ISSUE TITLE
Support building wheel

### ISSUE THREAD

**Issue by ccoulombe** [fenderglass/ABruijn#190] opened 2019-11-29 02:25 UTC
Hello,

`setup.py` does install but fails when building a wheel.

Command to reproduce (with `wheel` installed) : 
`(env) python setup.py bdist_wheel` or `(env) pip wheel .`

**Comment by ccoulombe** [comment] 2020-04-07 12:18
Any plans to support this soon? 
It would make it easier to distribute Flye (e.g. PyPI, supercomputers wheelhouses, etc.)

**Comment by mikolmogorov** [comment] 2020-04-12 19:40
Hi,

I looked into this - it seems that the issue is that Flye is using a workaround to include C++ binaries into an .egg package (via "scripts" option in setup.py). Looks like when building wheel, this scripts directory is not created (because there are no actual python scripts), which is causing the error.

Theoretically, I could push this workaround further, by tricking setuptools to create scripts directory. But this still be a workaround, and eventually will break. Are you aware of any official documentation wrt to including C++ binaries into a python package? 

Note that these are NOT "Python C extensions", but regular self-contained binaries. I am against converting them into library extensions because of various issue with portability and distribution I've experienced in the past.

Mikhail

**Comment by mikolmogorov** [comment] 2020-05-06 18:27
Ok, since there is no further input, I am marking this as "wontfix". Let me know if you have any ideas how to implement it the right way without significant changes in the project organization.

**Closed as completed by mikolmogorov** 2020-05-06 18:27 UTC
Labels: enhancement, wontfix

**Comment by zymergen-luke** [comment] 2022-02-14 22:06
I have a potential fix for this
