### ISSUE TITLE
Subassemblies: less contiguous, duplicate BUSCO

### ISSUE THREAD

**Issue by harish0201** [fenderglass/ABruijn#68] opened 2019-01-07 13:15 UTC
Hi!

I have merged two different assemblies, one from Canu and other from SuperNova, I was able to assemble over 95% of the genome by using the subassemblies option as I felt that both of them had competing N50s (~1.5Mb in each case).

My question is:

1. The N50 is now around 850Kb, but assembly itself shows that the breadth of genome has been recovered, ie we have reached 97% assembly from over 88-90% input in each case. Does the order of inputting the assemblies in the command matter, like it does in case of quickmerge? How does the assembler decide which contigs/scaffolds has to be retained?

2. The Busco scores have increased as well, but so has Duplicacy as well. What was around 1.5% has now increased to about 2.5%. What method would you suggest to resolve this?

3. Would it be possible to use the subassemblies option along with the input of raw reads/ corrected reads as well? Intuitively this feels as though this would increase the contiguity and reduce the number of contigs in the merged assembly though it would be computationally expensive.

4. The step 3 for polishing seems to fail with this error, with this commit (2.3.7-g17e01fd)

`[2019-01-07 13:09:59] INFO: Running Flye 2.3.7-g17e01fd
[2019-01-07 13:09:59] INFO: Resuming previous run
[2019-01-07 13:09:59] INFO: Polishing genome (1/3)
[2019-01-07 13:09:59] INFO: Running minimap2
[2019-01-07 13:12:25] INFO: Separating alignment into bubbles
[2019-01-07 13:15:00] INFO: Alignment error rate: 0.0172107255931
[2019-01-07 13:15:00] INFO: Correcting bubbles
0% [2019-01-07 13:15:02] ERROR: Command '['flye-polish', '-t', '64', '/mnt/pmgt/flye_subassm/3-polishing/bubbles_1.fasta', '/mnt/apps/Flye/flye/config/bin_cfg/pacbio_substitutions.mat', '/mnt/apps/Flye/flye/config/bin_cfg/pacbio_homopolymers.mat', '/mnt/pmgt/flye_subassm/3-polishing/consensus_1.fasta']' returned non-zero exit status -11`

However as per one of the previous threads, I did get the graph_final.fasta, so I can just polish it and continue.

**Comment by mikolmogorov** [comment] 2019-01-11 00:01
Hi,

1. Since the assemblies have different sizes, it is better to use NG50 (not N50) for comparison. N50 is expected to drop once the assembly size increases. The other consideration is that in case two assemblies are conflicting, Flye is likely to prefer neither of them and don't extend beyond the breakpoint (instead of arbitrarily breaking the tie). A simple trick you can do to put more "weight" on one of the assemblies is basically feed it twice as input (so it's "coverage" will be twice higher). This might help to increase contiguity at a cost of producing less conservative assembly. Otherwise the order of input is not important, the algorithms are the same as for normal read assembly.

2. In general we did not observe Flye producing a lot of duplicated sequence. Is your genome diploid? It might be that the merged assembly simply catches more alternative alleles.

3. No, mixing sequences with different error types is not supported. You can assemble raw reads with Flye and then add to the other assemblies.

4. Seems strange, it is likely that file with bubbles is empty/corrupted. Can you post the output of `ls -l 3-polishing`, and also `head 3-polishing/bubbles_1.fasta` and `tail 3-polishing/bubbles_1.fasta`. It might be that one of the python threads that generate bubbles failed (silently, this is a bug) - try to re-run polishing with less number of threads to see if it's the case.

**Comment by harish0201** [comment] 2019-01-14 20:15
Awesome, I'll get back. to you once I get back from PAG?

Are you still here? I might have missed you yesterday!

**Comment by mikolmogorov** [comment] 2019-01-15 02:11
Yes, I will be at PAG tomorrow and the day after - will be happy to chat!

**Comment by harish0201** [comment] 2019-01-15 03:41
Awesome! Shall we meet near the Pacific Salon 1 by 10AM.

**Comment by lsterck** [comment] 2019-01-15 10:08
Damn, what are the odds, been attending PAG for the past years but decided to skip this year (bad call apparently). Anyway : I'm having the same issue as mentioned above:

```
[2019-01-14 22:44:14] root: INFO: Alignment error rate: 0.0643331376157
[2019-01-14 22:44:14] root: INFO: Correcting bubbles
[2019-01-14 22:44:37] root: ERROR: Command '['flye-polish', '-t', '30', '/scratch/leuven/417/FlyeSubAssem/3-polishing/bubbles_1.fasta', '/vsc-mounts/gent-data/417/Flye/flye/config/bin_cfg/pacbio_substitutions.mat', '/vsc-mounts/gent-data/417/Flye/flye/config/bin_cfg/pacbio_homopolymers.mat', '/scratch/leuven/417/FlyeSubAssem/3-polishing/consensus_1.fasta']' returned non-zero exit status -11
```

output from ls -l 3-polishing
```
-rw-rw-r-- 1  58G Jan 14 22:04 minimap_1.sam
-rw-rw-r-- 1  48G Jan 14 22:43 bubbles_1.fasta
-rw-rw-r-- 1  18M Jan 14 22:44 consensus_1.fasta
```
head 3-polishing/bubbles_1.fasta 
```
>contig_10 0 3
TGGGTAGGTATATTGGAAAGAAGGACACCTGTAAC
>0
GGTATATTGGAAAGAAGGACACCTATAAC
>1
GGTATATTGGAAAGAAGGACACCTATAAC
>2
TGGGTAGGTATATTGGAAAGAAGGACACCTGTAAC
>contig_10 35 3
```

tail  3-polishing/bubbles_1.fasta 
```
>0
CATACTATCTCTCTA
>contig_99991 182392 1
CTATTCCATTCCCGAAC
>0
CTATTCCATTCCCGAAC
>contig_99991 182409 1
AGCGAGCGGGAAAAA
>0
AGCGAGCGGGAAAAA
```

Do let me know if you need other/more info.

thx in advance and enjoy the rest of PAG

**Comment by mikolmogorov** [comment] 2019-01-15 17:03
@harish0201 - sounds good.

@lsterck - is this `--subassemblies` mode as well? Can you send me the first 1Gb of bubbles_1.fasta file, so I can reproduce the issue?

**Comment by lsterck** [comment] 2019-01-15 20:10
Hi,
yes, sorry to not have that mentioned but it is indeed.
OK, I can do that. Is it OK if I put it online somewhere so you can download it?

thx.

**Comment by mikolmogorov** [comment] 2019-01-15 20:23
@lsterck thanks! sure, whichever is more convenient for you.

**Comment by lsterck** [comment] 2019-01-16 11:00
@fenderglass , here is a [link ](https://floppy.psb.ugent.be/index.php/s/96c6Z3NTkqzxTR3)to download the first Gb of the bubbles_1.fasta file .
Do let me know if I can assist in any other way.
thx in advance

**Comment by mikolmogorov** [comment] 2019-01-18 03:20
Thank you! Looks like the issue was non-ACGT characters in the input. I've pushed an update into the 'flye' branch that should fix the issue - you can restart your run with '--restart-from polishing'.

**Comment by lsterck** [comment] 2019-01-18 08:15
Hi @fenderglass ,

thanks for the quick fix!
I'm currently trying it out but I seem to have an issue with restarting the pipeline: it complains about "ERROR: Inconsistent pipelnie version" (and there is a typo in that message ;) )

anything I can do to resolve this , or will I have to start over from the beginning?

**Comment by mikolmogorov** [comment] 2019-01-18 09:24
Ah, I forgot that the new version of pipeline is inconsistent with the old one - too many changes.. I think the easiest way would be to restart from the beginning - sorry about that! Also note, that the file 2-repeat/graph_paths.fasta contains almost final assembly, since for subassembly mode polishing is not that important.

**Comment by lsterck** [comment] 2019-02-04 22:27
Just wanted to let you know that the fix you provided works and the pipeline now runs without any issues. thx.

however, with this new version I notice drastic differences in result compared to the previous version. I'm not sure if this newest version is already up for feedback and that I perhaps need to open a new issue for this.

**Comment by mikolmogorov** [comment] 2019-02-04 23:02
Thanks for letting me know. Yes, please open a new issue - closing this one.

**Closed as completed by mikolmogorov** 2019-02-04 23:02 UTC
