### ISSUE TITLE
no disjointigs for pacbio datasets

### ISSUE THREAD

**Issue by snayfach** [fenderglass/ABruijn#341] opened 2021-01-24 15:27 UTC
Hello - I'm trying to use flye to assemble PacBio metagenomes from the SRA. However, for about 1/3 of the datasets, no disjointigs are assembled and the program ends with an error.

Using the latest version of flye and the command I'm using is:
`flye -t 64 --plasmids --pacbio-raw $FASTQ --meta --out-dir flye-out/$NAME`

Here's a randomly selected list of SRA accessions where the assembly failed:
> SRX3049013: PACBIO_SMRT (PacBio RS II) run: 260,526 spots, 804.4M bases
> SRX2575237: PACBIO_SMRT (PacBio RS) run: 42,281 spots, 65M bases
> SRX4808260: PACBIO_SMRT (PacBio RS II) run: 222,976 spots, 656.4M bases
> SRX1557573: PACBIO_SMRT (PacBio RS) run: 163,482 spots, 1.3G bases
> SRX1557578: PACBIO_SMRT (PacBio RS) run: 163,482 spots, 1.4G bases

Here's the log file for SRX3049013:
[flye.log](https://github.com/fenderglass/Flye/files/5862524/flye.log)

**Comment by mikolmogorov** [comment] 2021-01-25 19:24
Duplicate of #128. Please see if anything discussed in #128 applies. Feel free to continue discussion there - in this case, please provide the detailed information about your dataset to get help.

**Closed as completed by mikolmogorov** 2021-01-25 19:24 UTC
Labels: duplicate
