### ISSUE TITLE
Error parsing bubbles file

### ISSUE THREAD

**Issue by life333** [fenderglass/ABruijn#592] opened 2023-04-12 07:39 UTC
Hello,

I get a following error during the polishing step:
I use "flye    --pacbio-raw  2.subreads.fasta  --out-dir ./ --genome-size 50m --threads 40" and found the error
[2023-04-12 14:52:57] INFO: Aligned read sequence: 5112856956 / 5869016802 (0.871161)
[2023-04-12 14:52:57] INFO: Median overlap divergence: 0.0975497
[2023-04-12 14:52:58] INFO: Mean edge coverage: 95
[2023-04-12 14:52:59] INFO: Simplifying the graph
[2023-04-12 14:53:33] INFO: >>>STAGE: contigger
[2023-04-12 14:53:33] INFO: Generating contigs
[2023-04-12 14:53:33] INFO: Reading sequences
[2023-04-12 14:54:39] INFO: Generated 1191 contigs
[2023-04-12 14:54:40] INFO: Added 4 scaffold connections
[2023-04-12 14:54:43] INFO: >>>STAGE: polishing
[2023-04-12 14:54:43] INFO: Polishing genome (1/1)
[2023-04-12 14:54:43] INFO: Running minimap2

[2023-04-12 15:04:36] INFO: Separating alignment into bubbles
[2023-04-12 15:11:13] INFO: Alignment error rate: 0.144062
[2023-04-12 15:11:13] INFO: Correcting bubbles
0% 10% terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing bubbles file
[2023-04-12 15:25:34] ERROR: Command '['flye-modules', 'polisher', '--bubbles', '/ifs1/User/yangyang/dockergene/lx/zl/40-polishing/bubbles_1.fasta', '--subs-mat', '/share/work/biosoft/python/Python3/lib/python3.8/site-packages/flye/config/bin_cfg/pacbio_chm13_substitutions.mat', '--hopo-mat', '/share/work/biosoft/python/Python3/lib/python3.8/site-packages/flye/config/bin_cfg/pacbio_chm13_homopolymers.mat', '--out', '/ifs1/User/yangyang/dockergene/lx/zl/40-polishing/consensus_1.fasta', '--threads', '40']' died with <Signals.SIGABRT: 6>.
[2023-04-12 15:25:34] ERROR: Pipeline aborted

Thank you for your help
Sibyl

**Comment by mikolmogorov** [comment] 2023-04-19 15:01
Duplicate of https://github.com/fenderglass/Flye/issues/584 - please continue the discussion in this thread.

Does your input fasta contains non-ACGT symbols? Could you try validating it with `seqtk`? To reproduce and fix the error, I would need a small sample of input that gives you the error - will you be able to come up with one?

Best,
Misha

**Closed as completed by mikolmogorov** 2023-04-19 15:01 UTC
