### ISSUE TITLE
ERROR: Caught unhandled exception: _Map_base::at

### ISSUE THREAD

**Issue by dvera** [fenderglass/ABruijn#61] opened 2018-10-25 21:57 UTC
Getting this error using all the standard packages from ubuntu 16. Any ideas how to troubleshoot? This was from the running of the assembly step with 2.3.6, the consensus step with 2.3.5, and attempting to do the repeat-resolving step with 2.3.6.

```bash
root@flye:/tank# flye --resume --pacbio-raw all.fastq --genome-size 3g --out-dir test5 --threads 28 --min-overlap 1000                                                                     
[2018-10-25 01:47:43] INFO: Running Flye 2.3.6-release
[2018-10-25 01:47:43] INFO: Resuming previous run
[2018-10-25 01:47:43] INFO: Performing repeat analysis
[2018-10-25 01:47:43] INFO: Reading sequences
[2018-10-25 02:36:20] INFO: Building repeat graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-25 04:04:59] INFO: Median overlap divergence: 0.0860884
[2018-10-25 07:43:52] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% htop
80% 90% 100% 
[2018-10-25 16:30:39] INFO: Aligned read sequence: 30697732989 / 64995215439 (0.472308)
[2018-10-25 16:30:39] INFO: Median overlap divergence: 0.162136
[2018-10-25 16:32:02] INFO: Mean edge coverage: 20
[2018-10-25 17:13:10] INFO: Resolving repeats
[2018-10-25 18:42:41] ERROR: Caught unhandled exception: _Map_base::at
[2018-10-25 18:42:41] ERROR:    flye-repeat(_Z16exceptionHandlerv+0xb4) [0x490554]
[2018-10-25 18:42:41] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d6b6) [0x7f9945c516b6]
[2018-10-25 18:42:41] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d701) [0x7f9945c51701]
[2018-10-25 18:42:41] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d919) [0x7f9945c51919]
[2018-10-25 18:42:41] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt20__throw_out_of_rangePKc+0x3f) [0x7f9945c7a2cf]
[2018-10-25 18:42:41] ERROR:    flye-repeat(_ZNK11RepeatGraph14complementPathERKSt6vectorIP9GraphEdgeSaIS2_EE+0x120) [0x483310]
[2018-10-25 18:42:41] ERROR:    flye-repeat(_ZN14RepeatResolver18resolveConnectionsERKSt6vectorINS_10ConnectionESaIS1_EEf+0xb89) [0x447359]
[2018-10-25 18:42:41] ERROR:    flye-repeat(_ZN14RepeatResolver14resolveRepeatsEv+0x66) [0x4486b6]
[2018-10-25 18:42:41] ERROR:    flye-repeat(main+0xa92) [0x434b72]
[2018-10-25 18:42:41] ERROR:    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f99450de830]
[2018-10-25 18:42:47] ERROR: Command '['flye-repeat', '-l', '/tank/test5/flye.log', '-t', '28', '-v', '1000', '-v', '1000', '-k', '17', '/tank/test5/1-consensus/consensus.fasta', 'all.fastq', '/tank/test5/2-repeat', '3000000000', '/usr/local/lib/python2.7/dist-packages/flye/config/bin_cfg/asm_raw_reads.cfg']' returned non-zero exit status 1
```

**Comment by mikolmogorov** [comment] 2018-10-29 04:11
Hi,

This basically is a sign that the graph at some point lost its consistency - but it is hard to tell exactly where. Must be some kind of  a corner case that we didn't consider.

Could you send me a full log of the run and tell a bit more about the dataset (it looks like it's older PacBio chemistry?) - you can reply me to fenderglass@gmail.com if you prefer.

**Comment by bbalog87** [comment] 2018-12-03 08:45
Hi @fenderglass ,

I have the same issue, but using --subassemblies. Flye was running on debian system.

```               
linu4/projekte/I3-PikeperchAssembly/Assembly> /usr/bin/flye --subassemblies ~/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/*.fa -g 1.3g -o flye-consensus/ -t 90 -i 2 -m 6500 
[2018-12-02 20:37:42] INFO: Running Flye 2.3.7-release
[2018-12-02 20:37:42] INFO: Configuring run
[2018-12-02 20:43:04] INFO: Input genome size: 1300000000
[2018-12-02 20:43:04] INFO: Estimated coverage: 8
[2018-12-02 20:43:04] INFO: Reads N50/N90: 826 / 154
[2018-12-02 20:43:04] INFO: Selected k-mer size: 31
[2018-12-02 20:43:04] INFO: Assembling reads
[2018-12-02 20:43:04] INFO: Reading sequences
[2018-12-02 20:47:40] INFO: Generating solid k-mer index
[2018-12-02 20:52:51] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-12-02 20:53:15] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70un70un% % 80% 90% 100% 
[2018-12-02 20:55:28] INFO: Filling index table
0% 10% 20% 30% 40llin40llin40llin% % % 50% 60% 70% 80% 90% 100% 
[2018-12-02 21:00:47] INFO: Extending reads
[2018-12-02 21:01:23] INFO: Overlap-based coverage: 0
[2018-12-02 21:01:23] INFO: Median overlap divergence: 0.000609385
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-12-03 02:32:51] INFO: Added 37326 singleton reads
[2018-12-03 02:32:51] INFO: Assembled 37326 draft contigs
[2018-12-03 02:33:04] INFO: Generating contig sequences
[2018-12-03 02:34:12] INFO: Performing repeat analysis
[2018-12-03 02:34:12] INFO: Reading sequences
[2018-12-03 02:40:16] INFO: Building repeat graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-12-03 03:02:42] INFO: Median overlap divergence: 0.0101632
[2018-12-03 03:03:31] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-12-03 03:14:06] INFO: Aligned read sequence: 3105457870 / 3131257672 (0.991761)
[2018-12-03 03:14:06] INFO: Median overlap divergence: 0.01048
[2018-12-03 03:14:24] INFO: Mean edge coverage: 2
[2018-12-03 03:17:34] INFO: Resolving repeats
[2018-12-03 03:18:08] INFO: Generating contigs
[2018-12-03 03:19:04] INFO: Generated 13202 contigs
[2018-12-03 03:19:35] ERROR: Caught unhandled exception: _Map_base::at
[2018-12-03 03:19:35] ERROR: 	flye-repeat(_Z16exceptionHandlerv+0xd0) [0x495840]
[2018-12-03 03:19:35] ERROR: 	/usr/lib64/libstdc++.so.6(+0x99e98) [0x7fc7fdad0e98]
[2018-12-03 03:19:35] ERROR: 	/usr/lib64/libstdc++.so.6(+0x99ee3) [0x7fc7fdad0ee3]
[2018-12-03 03:19:35] ERROR: 	/usr/lib64/libstdc++.so.6(+0x9a113) [0x7fc7fdad1113]
[2018-12-03 03:19:35] ERROR: 	/usr/lib64/libstdc++.so.6(+0x95ddb) [0x7fc7fdaccddb]
[2018-12-03 03:19:35] ERROR: 	flye-repeat(_ZNK11RepeatGraph14complementEdgeEP9GraphEdge+0xd9) [0x486469]
[2018-12-03 03:19:35] ERROR: 	flye-repeat(_ZN14ContigExtender25outputScaffoldConnectionsERKSs+0xcfa) [0x46a3fa]
[2018-12-03 03:19:35] ERROR: 	flye-repeat(main+0xac5) [0x43aec5]
[2018-12-03 03:19:35] ERROR: 	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fc7fcffb725]
[2018-12-03 03:19:35] ERROR: 	flye-repeat(_start+0x29) [0x43b8f9]
[2018-12-03 03:19:45] ERROR: Command '['flye-repeat', '-l', '/projekte/I3-PikeperchAssembly/Assembly/flye-consensus/flye.log', '-t', '90', '-v', '6500', '-v', '6500', '-k', '31', '/projekte/I3-PikeperchAssembly/Assembly/flye-consensus/0-assembly/draft_assembly.fasta', '/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/superReadSequences.named.fa,/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/zander.flye9.ctg.fa,/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/zander.mecat2.racon.noN.fa,/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/zander.pe.mp10kb.megahit.contigs.fa,/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/zander.platanus.ctg1k.fa,/home/fb3/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/Assembly/Flye-Assembly/Flye-Consensus/zander.wtdbg.ctg.fa', '/projekte/I3-PikeperchAssembly/Assembly/flye-consensus/2-repeat', '1300000000', '/usr/lib/python2.7/site-packages/flye/config/bin_cfg/asm_subasm.cfg']' returned non-zero exit status 1
```

**Comment by mikolmogorov** [comment] 2018-12-03 22:17
Thank you! Is it possible for you to send me the input sequences, so I can reproduce the problem? It is very hard to tell where this error actually occurred just using the log.

**Comment by bbalog87** [comment] 2018-12-04 17:23
Okay, I have sent you the input sequences at your email.

**Comment by mikolmogorov** [comment] 2018-12-06 19:48
Thank you! I think I know what might be the cause - I've just pushed a fix into the main repo branch. Please try and check if it works for your case.

**Comment by bbalog87** [comment] 2018-12-07 09:06
Your update (Flye 2.3.7-g17e01fd) has fixed the issue.  ```Flye --subassemblies``` is running without error.
Thank you!

**Closed as completed** 2018-12-07 17:33 UTC
