### ISSUE TITLE
assembly of a heterozygous plant

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#187] opened 2019-11-14 17:01 UTC
Hello,
The first flye assembly of my heterozygous (2.5 Gb haploid genome, repeat-rich, and with highly-divergent haplotypes) just completed and I have a few questions/comments about it.
The command was
`flye --nano-raw reads_all_8kb_q7.fa --genome-size 5g --out-dir flye_8kb_191004 -t 48 --min-overlap 10000` and the input data was Promethion reads, QV>7, reads all above 8 kb, N50 about 22 kb, about 35x cov of 5 Gb.

The total assembly size is 3.65 Gb, N50 688 kb, N90 130 kb - very good N metrics I think. The total size is at the low end, and my guess is that it is due to collapsed haplotypes. The distribution of the coverage values from the assembly_info.txt file is nicely bimodal:
<img width="350" alt="flye_cov" src="https://user-images.githubusercontent.com/13842014/68875870-ce8f1000-0703-11ea-8ef8-2def2f190a4d.PNG">
with several contigs at a coverage twice of the expected if the genome had 5 Gb. 

My thought is to take all the reads that align to the contigs with more than 55x cov (too bad there is no bam file left in the `40-polishing/` folder!) and assemble them (individually, by contig) with higher stringency, hoping to reconstruct the two alleles separately.
Do you think this makes sense? Would you tweak some parameters in the flye command? I am also thinking to use Canu (or something similar) to assemble the reads in a contig-specific way so that hopefully I can get error corrected reads that are 2n and intrinsically phased. Do you have any thoughts or suggestions on this?

Looking at the values of multiplicity and coverage, I see that there is not a great correlation between the two:
<img width="260" alt="flye_cov_mult" src="https://user-images.githubusercontent.com/13842014/68877861-0b103b00-0707-11ea-96c5-e95c566b6edc.PNG">
what is the best use we can make of the multiplicity value?
I guess the coverage is an average value across the whole contig - do you think that e.g. a contig with 70x cov will have a region that is collapsed (80x) and one that is at 40x?
The bam file from the realignment of the reads will tell us that.

Then, I noticed that some contigs contain nodes that are repeated multiple times:
```#seq_name       length  cov.    circ.   repeat  mult.   graph_path
contig_1        1179895 46      -       -       1       19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,19687,-6921,19687,19687,2609,1,23733,23530,-19144,-5994,24485,-5450,5992,5992,5991,-22468,4629,-18990,4686,-24290,-5626,-19144,-19015,4686,-24290,-5626,-19144,-5994,24485,-5450,5992,5992,5991,-22468,4629,-18990,4686,-24290,-11619,-5994,24485,-5450,5992,5991,-22468,4629,-18990,4686,-24290,-11619,-5994,24485
contig_8        768465  48      -       -       1       -6158,-6158,-6158,-6158,-6158,-6158,-6158,-6158,-6158,-6158,-6158,-6158,-10248,-8429,-8429,8,-6055,-6055,-6055,-18752,21618,-5853,13661,-7313,7617,-21477
contig_10       1821999 46      -       -       1       8276,8276,8276,-8168,-8168,-8168,-8168,11060,18011,7040,-14675,14292,7211,7211,23529,23529,23529,8276,10,17620
contig_11       516464  51      -       -       1       -6236,-20461,-5500,11,-8519,8429,10248,6158,6158,6158,6158,6158,6158,6158,6158
contig_13       683002  45      -       -       1       14647,-16934,8052,8052,18561,-16934,22182,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,-7346,1890,13,*
contig_15       131793  38      -       -       1       *,15,-16289,-16289,-16289,-16289,-16289,-16289,-16289,-16289,13202,-9392,-9392,-9392,-9392,-9392,12115,-16289,-16289,-16289,-16289,-16289,-16289,-16289,-16289
contig_17       172421  44      -       -       1       17,-6188,15248,7539,10763,-13949,11268,-13949,4300,4300
contig_18       898724  44      -       -       1       18,12287,12287,12287,12287,14443,-7453,-7453,-7453,-7453,-7453,-7453,-7453,-7453,8537,8537,8537,8537,8537,-20109
contig_21       1088262 43      -       -       1       7841,7841,7841,7841,-7200,7081,-22397,-7878,7841,7841,7841,7841,7841,7841,7841,21,-13711,-13711,-13711,-13711,23845,7707,7707,-10546,-10546,-10546
contig_28       119289  35      -       -       1       -16612,-16612,-16612,-11263,-21562,-12824,23659,7089,-5911,28,7346,7346,7346,7346,7346,7346,7346,7346,7346,7346,7346,7346,23392,-4718,20747,5180,-7135,-7135,-7135
contig_32       798544  41      -       -       1       -6107,-6107,-6107,-6107,6106,-18536,-12043,12277,12277,12277,32,-16151,-20827,-1648,-5751,-12333,-11095,-3387,10595
```
is this normal? Are those tandem repeats that were not resolved in separate sequences?
I still have to inspect the assembly graph.

Lastly, for this run my input file size was limited by the amount of memory that the k-mer step was taking (at the very beginning of the assembly): I had to remove shorter reads (going up to 8 kb or larger) to fit within the 1 TB I have available. 
Is there any other way I could still count all k-mers with a bit more data? I could add another 8x per haplotype, and that may help distinguish SNPs from sequencing errors and have less collapsed haplotypes.
It would be convenient to play with memory at this stage, since all the subsequent steps go with about 200 GB only?
Thanks,

Dario

**Comment by mikolmogorov** [comment] 2019-11-20 06:17
Hi Dario,

Thanks for the detailed feedback! 

>The total size is at the low end, and my guess is that it is due to collapsed haplotypes. 

Very likely. Do you know the expected divergence rate? Flye can definitely collapse regions with a few % divergence. Also, even if *mean* heterozygosity is high, some haplotype regions could still be very similar  - and therefore collapsed. Generating complete haplotypes from long-read data only is in general still poorly solved, currently. 

>My thought is to take all the reads that align to the contigs with more than 55x cov (too bad there is no bam file left in the 40-polishing/ folder!) and assemble them (individually, by contig) with higher stringency, hoping to reconstruct the two alleles separately.

It sounds like a good idea if you want to try to use other methods for these regions only (for example, FALCON). Just applying Flye again probably will result into a similar assembly. But re-assembly of Canu error-corrected reads with Flye might help.

>Looking at the values of multiplicity and coverage, I see that there is not a great correlation between the two:

Looks weird, in the most cases multiplicity should be simply edge_coverage / genome_coverage. Might be a bug in Flye output - I will take a look.

>is this normal? Are those tandem repeats that were not resolved in separate sequences?

Exactly, those are flanking repeats that appear in multiple copies (and were not resolved).

>Is there any other way I could still count all k-mers with a bit more data? 

Unfortunately current implementation does not allow this. The problem is rather keeping the k-mer index in memory for finding overlaps, rather than counting. On the other hand, you always can add extra reads at the repeat resolution stage. Just use the option `--resolve-from repeat`, and supply the full set of reads, instead of the filtered one.

Hope this helps, let me know if you have more questions.
Mikhail

**Comment by mikolmogorov** [comment] 2019-12-04 05:31
Ok, I think I did find and fix the problem with multiplicity calculation after polishing. Marking as closed.

**Closed as completed by mikolmogorov** 2019-12-04 05:31 UTC
Labels: question
