### ISSUE TITLE
No disjointigs were assembled - please check if the read type and genome size parameters are correct

### ISSUE THREAD

**Issue by PavithraV0223** [fenderglass/ABruijn#600] opened 2023-05-01 07:55 UTC
Hello, I'm working with the Nanopore data, of the alpacas. I have tried all the different parameters but each run gives me the same error. I'm unsure what the problem is. I have been using the adapter and barcode trimmed fastq file as an input to nano-raw.  
I have provided my log file for your reference. I have tried using the meta and the normal mode as well. You're help would be much appreciated. 
2023-04-27 12:58:27] root: INFO: Starting Flye 2.9.2-b1786
[2023-04-27 12:58:27] root: DEBUG: Cmd: /home/pavi/miniconda3/bin/flye --nano-raw /home/pavi/flye/fitered3_MinIONadapt.fastq --out-dir ./flye_output
[2023-04-27 12:58:27] root: DEBUG: Python version: 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0]
[2023-04-27 12:58:27] root: INFO: >>>STAGE: configure
[2023-04-27 12:58:27] root: INFO: Configuring run
[2023-04-27 12:58:28] root: INFO: Total read length: 252562133
[2023-04-27 12:58:28] root: INFO: Reads N50/N90: 1137 / 994
[2023-04-27 12:58:28] root: INFO: Minimum overlap set to 1000
[2023-04-27 12:58:28] root: INFO: >>>STAGE: assembly
[2023-04-27 12:58:28] root: INFO: Assembling disjointigs
[2023-04-27 12:58:28] root: DEBUG: -----Begin assembly log------
[2023-04-27 12:58:28] root: DEBUG: Running: flye-modules assemble --reads /home/pavi/flye/fitered3_MinIONadapt.fastq --out-asm /home/pavi/flye/flye_output/00-assembly/draft_assembly.fasta --config /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg --log /home/pavi/flye/flye_output/flye.log --threads 1 --min-ovlp 1000
[2023-04-27 12:58:28] DEBUG: Build date: Mar 27 2023 14:17:04
[2023-04-27 12:58:28] DEBUG: Total RAM: 22 Gb
[2023-04-27 12:58:28] DEBUG: Available RAM: 19 Gb
[2023-04-27 12:58:28] DEBUG: Total CPUs: 7
[2023-04-27 12:58:28] DEBUG: Loading /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg
[2023-04-27 12:58:28] DEBUG: Loading /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_defaults.cfg
[2023-04-27 12:58:28] DEBUG: 	big_genome_threshold=29000000
[2023-04-27 12:58:28] DEBUG: 	meta_read_filter_kmer_freq=100
[2023-04-27 12:58:28] DEBUG: 	chain_large_gap_penalty=2
[2023-04-27 12:58:28] DEBUG: 	chain_small_gap_penalty=0.5
[2023-04-27 12:58:28] DEBUG: 	chain_gap_jump_threshold=100
[2023-04-27 12:58:28] DEBUG: 	max_coverage_drop_rate=5
[2023-04-27 12:58:28] DEBUG: 	max_extensions_drop_rate=5
[2023-04-27 12:58:28] DEBUG: 	chimera_window=100
[2023-04-27 12:58:28] DEBUG: 	chimera_overhang=1000
[2023-04-27 12:58:28] DEBUG: 	min_reads_in_disjointig=4
[2023-04-27 12:58:28] DEBUG: 	max_inner_reads=10
[2023-04-27 12:58:28] DEBUG: 	max_inner_fraction=0.25
[2023-04-27 12:58:28] DEBUG: 	max_separation=500
[2023-04-27 12:58:28] DEBUG: 	unique_edge_length=50000
[2023-04-27 12:58:28] DEBUG: 	min_repeat_res_support=0.51
[2023-04-27 12:58:28] DEBUG: 	out_paths_ratio=5
[2023-04-27 12:58:28] DEBUG: 	graph_cov_drop_rate=5
[2023-04-27 12:58:28] DEBUG: 	coverage_estimate_window=100
[2023-04-27 12:58:28] DEBUG: 	max_bubble_length=50000
[2023-04-27 12:58:28] DEBUG: 	loop_coverage_rate=1.5
[2023-04-27 12:58:28] DEBUG: 	repeat_edge_cov_mult=1.75
[2023-04-27 12:58:28] DEBUG: 	weak_detach_rate=5
[2023-04-27 12:58:28] DEBUG: 	tip_coverage_rate=2
[2023-04-27 12:58:28] DEBUG: 	tip_length_rate=2
[2023-04-27 12:58:28] DEBUG: 	output_gfa_before_rr=0
[2023-04-27 12:58:28] DEBUG: 	remove_alt_edges=0
[2023-04-27 12:58:28] DEBUG: 	low_cutoff_warning=1
[2023-04-27 12:58:28] DEBUG: 	kmer_size=17
[2023-04-27 12:58:28] DEBUG: 	use_minimizers=0
[2023-04-27 12:58:28] DEBUG: 	reads_base_alignment=0
[2023-04-27 12:58:28] DEBUG: 	meta_read_top_kmer_rate=0.40
[2023-04-27 12:58:28] DEBUG: 	maximum_jump=1500
[2023-04-27 12:58:28] DEBUG: 	maximum_overhang=1500
[2023-04-27 12:58:28] DEBUG: 	repeat_kmer_rate=100
[2023-04-27 12:58:28] DEBUG: 	assemble_ovlp_divergence=0.10
[2023-04-27 12:58:28] DEBUG: 	assemble_divergence_relative=1
[2023-04-27 12:58:28] DEBUG: 	repeat_graph_ovlp_divergence=0.08
[2023-04-27 12:58:28] DEBUG: 	read_align_ovlp_divergence=0.25
[2023-04-27 12:58:28] DEBUG: 	hpc_scoring_on=0
[2023-04-27 12:58:28] DEBUG: 	add_unassembled_reads=0
[2023-04-27 12:58:28] DEBUG: 	extend_contigs_with_repeats=0
[2023-04-27 12:58:28] DEBUG: 	min_read_cov_cutoff=3
[2023-04-27 12:58:28] DEBUG: 	short_tip_length=20000
[2023-04-27 12:58:28] DEBUG: 	long_tip_length=100000
[2023-04-27 12:58:28] DEBUG: Running with k-mer size: 17
[2023-04-27 12:58:28] DEBUG: Running with minimum overlap 1000
[2023-04-27 12:58:28] DEBUG: Metagenome mode: N
[2023-04-27 12:58:28] DEBUG: Short mode: N
[2023-04-27 12:58:28] INFO: Reading sequences
[2023-04-27 12:58:29] DEBUG: Building positional index
[2023-04-27 12:58:29] DEBUG: Total sequence: 224735072 bp
[2023-04-27 12:58:31] INFO: Counting k-mers:
[2023-04-27 12:59:01] DEBUG: Updating k-mer histogram
[2023-04-27 12:59:39] DEBUG: Hash size: 1033102
[2023-04-27 12:59:39] DEBUG: Total k-mers 40609435
[2023-04-27 12:59:39] INFO: Filling index table (1/2)
[2023-04-27 13:00:49] DEBUG: Mean k-mer frequency: 340.156
[2023-04-27 13:00:49] DEBUG: Repetitive k-mer frequency: 34015
[2023-04-27 13:00:49] DEBUG: Filtered 28293692 repetitive k-mers (0.319157)
[2023-04-27 13:00:49] INFO: Filling index table (2/2)
[2023-04-27 13:01:59] DEBUG: Sorting k-mer index
[2023-04-27 13:02:00] DEBUG: Selected k-mers: 354076
[2023-04-27 13:02:00] DEBUG: Index size: 60427371
[2023-04-27 13:02:00] DEBUG: Mean k-mer index frequency: 170.662
[2023-04-27 13:02:00] DEBUG: Peak RAM usage: 8 Gb
[2023-04-27 13:02:00] DEBUG: Estimating k-mer identity bias
[2023-04-27 13:04:53] DEBUG: Initial divergence estimate : 0.234128
[2023-04-27 13:04:53] DEBUG: Relative threshold: Y
[2023-04-27 13:04:53] DEBUG: Max divergence threshold set to 0.334128
[2023-04-27 13:04:53] INFO: Extending reads
[2023-04-27 13:04:53] DEBUG: Estimating overlap coverage
[2023-04-27 13:07:48] INFO: Overlap-based coverage: 205
[2023-04-27 13:07:48] INFO: Median overlap divergence: 0.234818
[2023-04-27 13:07:48] DEBUG: Sequence divergence distribution: 

    |                                                 *                |                                 
    |                                                 *                |                                 
    |                                             *   *                |                                 
    |                                             * * * *              |                                 
    |                                             * * * *              |                                 
    |                                             *** * * *            |                                 
    |                                            **** * * *            |                                 
    |                                           ******* ****           |                                 
    |                                           ************           |                                 
    |                                          **************          |                                 
    |                                          **************          |                                 
    |                                       *  **************          |                                 
    |                                       *****************          |                                 
    |                                      ******************          |                                 
    |                                      ******************          |                                 
    |                                    ********************          |                                 
    |                       *   *        **********************        |                                 
    |                       * *** ** * *************************       |                                 
    |                 *********************************************  * |      *                          
    |            ******************************************************|**   ** *                        
    ----------------------------------------------------------------------------------------------------
    0%        5%        10%       15%       20%       25%       30%       35%       40%       45%       

    Q25 = 0.21, Q50 = 0.23, Q75 = 0.26

[2023-04-27 22:07:06] INFO: Assembled 0 disjointigs
[2023-04-27 22:07:06] INFO: Generating sequence
[2023-04-27 22:07:06] DEBUG: Building positional index
[2023-04-27 22:07:06] DEBUG: Mean k-mer frequency: 0
[2023-04-27 22:07:06] DEBUG: Repetitive k-mer frequency: 0
[2023-04-27 22:07:06] DEBUG: Filtered 0 repetitive k-mers (-nan)
[2023-04-27 22:07:06] DEBUG: Sorting k-mer index
[2023-04-27 22:07:06] DEBUG: Selected k-mers: 0
[2023-04-27 22:07:06] DEBUG: K-mer index size: 0
[2023-04-27 22:07:06] DEBUG: Mean k-mer frequency: -nan
[2023-04-27 22:07:06] DEBUG: Minimizer rate: -nan
[2023-04-27 22:07:06] INFO: Filtering contained disjointigs
[2023-04-27 22:07:06] DEBUG: Computing transitive closure for overlaps
[2023-04-27 22:07:06] DEBUG: Found 0 overlaps
[2023-04-27 22:07:06] DEBUG: Left 0 overlaps after filtering
[2023-04-27 22:07:06] INFO: Contained seqs: 0
[2023-04-27 22:07:06] DEBUG: Writing FASTA
[2023-04-27 22:07:06] DEBUG: Peak RAM usage: 8 Gb
-----------End assembly log------------
[2023-04-27 22:07:06] root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2023-04-27 22:07:06] root: ERROR: Pipeline aborted

**Comment by mikolmogorov** [comment] 2023-05-02 16:07
Duplicate of https://github.com/fenderglass/Flye/issues/128. Please see if anything applies, and if not please continue the discussion there.

**Closed as completed by mikolmogorov** 2023-05-02 16:07 UTC

**Comment by PavithraV0223** [comment] 2023-05-03 07:43
Hello, I'm working with the Nanopore data, of the alpacas. I have tried all the different parameters but each run gives the same error. I'm unsure what the problem is. I have been using the adapter and barcode trimmed fastq file as an input to nano-raw. I have tried all the trouble shooting as mentioned above in the discussion but ending up with the same error. 
I have provided my log file for your reference. I have tried using the meta and the normal mode as well. You're help would be much appreciated.
2023-04-27 12:58:27] root: INFO: Starting Flye 2.9.2-b1786
[2023-04-27 12:58:27] root: DEBUG: Cmd: /home/pavi/miniconda3/bin/flye --nano-raw /home/pavi/flye/fitered3_MinIONadapt.fastq --out-dir ./flye_output
[2023-04-27 12:58:27] root: DEBUG: Python version: 3.7.16 (default, Jan 17 2023, 22:20:44)
[GCC 11.2.0]
[2023-04-27 12:58:27] root: INFO: >>>STAGE: configure
[2023-04-27 12:58:27] root: INFO: Configuring run
[2023-04-27 12:58:28] root: INFO: Total read length: 252562133
[2023-04-27 12:58:28] root: INFO: Reads N50/N90: 1137 / 994
[2023-04-27 12:58:28] root: INFO: Minimum overlap set to 1000
[2023-04-27 12:58:28] root: INFO: >>>STAGE: assembly
[2023-04-27 12:58:28] root: INFO: Assembling disjointigs
[2023-04-27 12:58:28] root: DEBUG: -----Begin assembly log------
[2023-04-27 12:58:28] root: DEBUG: Running: flye-modules assemble --reads /home/pavi/flye/fitered3_MinIONadapt.fastq --out-asm /home/pavi/flye/flye_output/00-assembly/draft_assembly.fasta --config /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg --log /home/pavi/flye/flye_output/flye.log --threads 1 --min-ovlp 1000
[2023-04-27 12:58:28] DEBUG: Build date: Mar 27 2023 14:17:04
[2023-04-27 12:58:28] DEBUG: Total RAM: 22 Gb
[2023-04-27 12:58:28] DEBUG: Available RAM: 19 Gb
[2023-04-27 12:58:28] DEBUG: Total CPUs: 7
[2023-04-27 12:58:28] DEBUG: Loading /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg
[2023-04-27 12:58:28] DEBUG: Loading /home/pavi/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_defaults.cfg
[2023-04-27 12:58:28] DEBUG: big_genome_threshold=29000000
[2023-04-27 12:58:28] DEBUG: meta_read_filter_kmer_freq=100
[2023-04-27 12:58:28] DEBUG: chain_large_gap_penalty=2
[2023-04-27 12:58:28] DEBUG: chain_small_gap_penalty=0.5
[2023-04-27 12:58:28] DEBUG: chain_gap_jump_threshold=100
[2023-04-27 12:58:28] DEBUG: max_coverage_drop_rate=5
[2023-04-27 12:58:28] DEBUG: max_extensions_drop_rate=5
[2023-04-27 12:58:28] DEBUG: chimera_window=100
[2023-04-27 12:58:28] DEBUG: chimera_overhang=1000
[2023-04-27 12:58:28] DEBUG: min_reads_in_disjointig=4
[2023-04-27 12:58:28] DEBUG: max_inner_reads=10
[2023-04-27 12:58:28] DEBUG: max_inner_fraction=0.25
[2023-04-27 12:58:28] DEBUG: max_separation=500
[2023-04-27 12:58:28] DEBUG: unique_edge_length=50000
[2023-04-27 12:58:28] DEBUG: min_repeat_res_support=0.51
[2023-04-27 12:58:28] DEBUG: out_paths_ratio=5
[2023-04-27 12:58:28] DEBUG: graph_cov_drop_rate=5
[2023-04-27 12:58:28] DEBUG: coverage_estimate_window=100
[2023-04-27 12:58:28] DEBUG: max_bubble_length=50000
[2023-04-27 12:58:28] DEBUG: loop_coverage_rate=1.5
[2023-04-27 12:58:28] DEBUG: repeat_edge_cov_mult=1.75
[2023-04-27 12:58:28] DEBUG: weak_detach_rate=5
[2023-04-27 12:58:28] DEBUG: tip_coverage_rate=2
[2023-04-27 12:58:28] DEBUG: tip_length_rate=2
[2023-04-27 12:58:28] DEBUG: output_gfa_before_rr=0
[2023-04-27 12:58:28] DEBUG: remove_alt_edges=0
[2023-04-27 12:58:28] DEBUG: low_cutoff_warning=1
[2023-04-27 12:58:28] DEBUG: kmer_size=17
[2023-04-27 12:58:28] DEBUG: use_minimizers=0
[2023-04-27 12:58:28] DEBUG: reads_base_alignment=0
[2023-04-27 12:58:28] DEBUG: meta_read_top_kmer_rate=0.40
[2023-04-27 12:58:28] DEBUG: maximum_jump=1500
[2023-04-27 12:58:28] DEBUG: maximum_overhang=1500
[2023-04-27 12:58:28] DEBUG: repeat_kmer_rate=100
[2023-04-27 12:58:28] DEBUG: assemble_ovlp_divergence=0.10
[2023-04-27 12:58:28] DEBUG: assemble_divergence_relative=1
[2023-04-27 12:58:28] DEBUG: repeat_graph_ovlp_divergence=0.08
[2023-04-27 12:58:28] DEBUG: read_align_ovlp_divergence=0.25
[2023-04-27 12:58:28] DEBUG: hpc_scoring_on=0
[2023-04-27 12:58:28] DEBUG: add_unassembled_reads=0
[2023-04-27 12:58:28] DEBUG: extend_contigs_with_repeats=0
[2023-04-27 12:58:28] DEBUG: min_read_cov_cutoff=3
[2023-04-27 12:58:28] DEBUG: short_tip_length=20000
[2023-04-27 12:58:28] DEBUG: long_tip_length=100000
[2023-04-27 12:58:28] DEBUG: Running with k-mer size: 17
[2023-04-27 12:58:28] DEBUG: Running with minimum overlap 1000
[2023-04-27 12:58:28] DEBUG: Metagenome mode: N
[2023-04-27 12:58:28] DEBUG: Short mode: N
[2023-04-27 12:58:28] INFO: Reading sequences
[2023-04-27 12:58:29] DEBUG: Building positional index
[2023-04-27 12:58:29] DEBUG: Total sequence: 224735072 bp
[2023-04-27 12:58:31] INFO: Counting k-mers:
[2023-04-27 12:59:01] DEBUG: Updating k-mer histogram
[2023-04-27 12:59:39] DEBUG: Hash size: 1033102
[2023-04-27 12:59:39] DEBUG: Total k-mers 40609435
[2023-04-27 12:59:39] INFO: Filling index table (1/2)
[2023-04-27 13:00:49] DEBUG: Mean k-mer frequency: 340.156
[2023-04-27 13:00:49] DEBUG: Repetitive k-mer frequency: 34015
[2023-04-27 13:00:49] DEBUG: Filtered 28293692 repetitive k-mers (0.319157)
[2023-04-27 13:00:49] INFO: Filling index table (2/2)
[2023-04-27 13:01:59] DEBUG: Sorting k-mer index
[2023-04-27 13:02:00] DEBUG: Selected k-mers: 354076
[2023-04-27 13:02:00] DEBUG: Index size: 60427371
[2023-04-27 13:02:00] DEBUG: Mean k-mer index frequency: 170.662
[2023-04-27 13:02:00] DEBUG: Peak RAM usage: 8 Gb
[2023-04-27 13:02:00] DEBUG: Estimating k-mer identity bias
[2023-04-27 13:04:53] DEBUG: Initial divergence estimate : 0.234128
[2023-04-27 13:04:53] DEBUG: Relative threshold: Y
[2023-04-27 13:04:53] DEBUG: Max divergence threshold set to 0.334128
[2023-04-27 13:04:53] INFO: Extending reads
[2023-04-27 13:04:53] DEBUG: Estimating overlap coverage
[2023-04-27 13:07:48] INFO: Overlap-based coverage: 205
[2023-04-27 13:07:48] INFO: Median overlap divergence: 0.234818
[2023-04-27 13:07:48] DEBUG: Sequence divergence distribution:

|                                                 *                |                                 
|                                                 *                |                                 
|                                             *   *                |                                 
|                                             * * * *              |                                 
|                                             * * * *              |                                 
|                                             *** * * *            |                                 
|                                            **** * * *            |                                 
|                                           ******* ****           |                                 
|                                           ************           |                                 
|                                          **************          |                                 
|                                          **************          |                                 
|                                       *  **************          |                                 
|                                       *****************          |                                 
|                                      ******************          |                                 
|                                      ******************          |                                 
|                                    ********************          |                                 
|                       *   *        **********************        |                                 
|                       * *** ** * *************************       |                                 
|                 *********************************************  * |      *                          
|            ******************************************************|**   ** *                        
----------------------------------------------------------------------------------------------------
0%        5%        10%       15%       20%       25%       30%       35%       40%       45%       

Q25 = 0.21, Q50 = 0.23, Q75 = 0.26
[2023-04-27 22:07:06] INFO: Assembled 0 disjointigs
[2023-04-27 22:07:06] INFO: Generating sequence
[2023-04-27 22:07:06] DEBUG: Building positional index
[2023-04-27 22:07:06] DEBUG: Mean k-mer frequency: 0
[2023-04-27 22:07:06] DEBUG: Repetitive k-mer frequency: 0
[2023-04-27 22:07:06] DEBUG: Filtered 0 repetitive k-mers (-nan)
[2023-04-27 22:07:06] DEBUG: Sorting k-mer index
[2023-04-27 22:07:06] DEBUG: Selected k-mers: 0
[2023-04-27 22:07:06] DEBUG: K-mer index size: 0
[2023-04-27 22:07:06] DEBUG: Mean k-mer frequency: -nan
[2023-04-27 22:07:06] DEBUG: Minimizer rate: -nan
[2023-04-27 22:07:06] INFO: Filtering contained disjointigs
[2023-04-27 22:07:06] DEBUG: Computing transitive closure for overlaps
[2023-04-27 22:07:06] DEBUG: Found 0 overlaps
[2023-04-27 22:07:06] DEBUG: Left 0 overlaps after filtering
[2023-04-27 22:07:06] INFO: Contained seqs: 0
[2023-04-27 22:07:06] DEBUG: Writing FASTA
[2023-04-27 22:07:06] DEBUG: Peak RAM usage: 8 Gb
-----------End assembly log------------
[2023-04-27 22:07:06] root: ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2023-04-27 22:07:06] root: ERROR: Pipeline aborted
