### ISSUE TITLE
Caught unhandled exception: _Map_base::at  flye=2.5

### ISSUE THREAD

**Issue by zzlzef** [fenderglass/ABruijn#159] opened 2019-09-24 14:48 UTC
Hi,
I got this error when using Flye=2.5, I found some people had the same problem with the old version, how can i solve the problem?

thank you very much!

[2019-09-21 15:24:24] INFO: Starting Flye 2.5-release
[2019-09-21 15:24:24] INFO: >>>STAGE: configure
[2019-09-21 15:24:24] INFO: Configuring run
[2019-09-21 16:32:10] INFO: Total read length: 262609844377
[2019-09-21 16:32:10] INFO: Input genome size: 1000000000
[2019-09-21 16:32:10] INFO: Estimated coverage: 262
[2019-09-21 16:32:10] INFO: Reads N50/N90: 27352 / 11896
[2019-09-21 16:32:10] INFO: Minimum overlap set to 5000
[2019-09-21 16:32:10] INFO: Selected k-mer size: 17
[2019-09-21 16:32:11] INFO: >>>STAGE: assembly
[2019-09-21 16:32:11] INFO: Assembling disjointigs
[2019-09-21 16:32:12] INFO: Reading sequences
[2019-09-21 17:37:27] INFO: Generating solid k-mer index
[2019-09-21 17:43:00] INFO: Counting k-mers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-21 17:57:12] INFO: Counting k-mers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-21 21:02:13] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-22 01:40:36] INFO: Extending reads
[2019-09-22 02:26:19] INFO: Overlap-based coverage: 128
[2019-09-22 02:26:19] INFO: Median overlap divergence: 0.172742
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-23 17:27:04] INFO: Assembled 1355 disjointigs
[2019-09-23 17:31:58] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-23 18:25:10] INFO: >>>STAGE: consensus
[2019-09-23 18:25:43] INFO: Running Minimap2
[2019-09-23 23:42:28] INFO: Computing consensus
[2019-09-24 02:21:19] INFO: Alignment error rate: 0.188309766469
[2019-09-24 02:21:39] INFO: >>>STAGE: repeat
[2019-09-24 02:21:39] INFO: Building and resolving repeat graph
[2019-09-24 02:21:41] INFO: Reading sequences
[2019-09-24 02:57:16] INFO: Building repeat graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-24 03:18:30] INFO: Median overlap divergence: 0.0737032
[2019-09-24 03:19:18] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-09-24 07:36:29] INFO: Aligned read sequence: 238373316845 / 256872752454 (0.927982)
[2019-09-24 07:36:29] INFO: Median overlap divergence: 0.149826
[2019-09-24 07:38:43] INFO: Mean edge coverage: 195
[2019-09-24 07:44:18] INFO: Resolving repeats
[2019-09-24 08:13:24] INFO: >>>STAGE: trestle
[2019-09-24 09:12:07] INFO: Simple unbridged repeats: 8
[2019-09-24 09:28:09] INFO: Resolved: 7
[2019-09-24 09:28:24] INFO: >>>STAGE: contigger
[2019-09-24 09:28:24] INFO: Generating contigs
[2019-09-24 09:28:25] INFO: Reading sequences
[2019-09-24 10:10:43] INFO: Generated 5803 contigs
[2019-09-24 10:10:54] ERROR: Caught unhandled exception: _Map_base::at
[2019-09-24 10:10:54] ERROR: 	flye-contigger(+0xa7c6c) [0x562d5bc89c6c]
[2019-09-24 10:10:54] ERROR: 	/public/home/zlzhu/anaconda3/envs/flye/bin/../lib/libstdc++.so.6(+0xabf47) [0x2ae42dc9df47]
[2019-09-24 10:10:54] ERROR: 	/public/home/zlzhu/anaconda3/envs/flye/bin/../lib/libstdc++.so.6(+0xabf7d) [0x2ae42dc9df7d]
[2019-09-24 10:10:54] ERROR: 	/public/home/zlzhu/anaconda3/envs/flye/bin/../lib/libstdc++.so.6(__cxa_rethrow+0) [0x2ae42dc9e15a]
[2019-09-24 10:10:54] ERROR: 	/public/home/zlzhu/anaconda3/envs/flye/bin/../lib/libstdc++.so.6(_ZSt20__throw_out_of_rangePKc+0x35) [0x2ae42dc9b087]
[2019-09-24 10:10:54] ERROR: 	flye-contigger(+0x54ed3) [0x562d5bc36ed3]
[2019-09-24 10:10:54] ERROR: 	flye-contigger(+0x481c6) [0x562d5bc2a1c6]
[2019-09-24 10:10:54] ERROR: 	flye-contigger(+0x12613) [0x562d5bbf4613]
[2019-09-24 10:10:54] ERROR: 	flye-contigger(+0x8d9e) [0x562d5bbead9e]
[2019-09-24 10:10:54] ERROR: 	/lib64/libc.so.6(__libc_start_main+0xf5) [0x2ae42e318445]
[2019-09-24 10:14:15] ERROR: Command '['flye-contigger', '--graph-edges', '/public/home/zlzhu/data/Genome_Data/flye_test/flye_output/21-trestle/repeat_graph_edges.fasta', '--reads', '/public/home/zlzhu/data/Genome_Data/1_B01/all_sequence.fasta', '--out-dir', '/public/home/zlzhu/data/Genome_Data/flye_test/flye_output/30-contigger', '--config', '/public/home/zlzhu/anaconda3/envs/flye/lib/python2.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--repeat-graph', '/public/home/zlzhu/data/Genome_Data/flye_test/flye_output/21-trestle/repeat_graph_dump', '--graph-aln', '/public/home/zlzhu/data/Genome_Data/flye_test/flye_output/20-repeat/read_alignment_dump', '--log', '/public/home/zlzhu/data/Genome_Data/flye_test/flye_output/flye.log', '--threads', '120', '--min-ovlp', '5000', '--kmer', '17']' returned non-zero exit status -6

**Comment by mikolmogorov** [comment] 2019-09-25 23:15
Duplicate of #160

**Closed as completed by mikolmogorov** 2019-09-25 23:15 UTC
