### ISSUE TITLE
A small contig generated when assembling a complete bacterial genome.

### ISSUE THREAD

**Issue by ranitori** [fenderglass/ABruijn#373] opened 2021-03-30 06:54 UTC
Hi,
For some background, issue #296 is similar to mine, but there are a few differences. I also tried one of the solutions noted there, but it made no difference to the results.

Relevant info:
* Flye 2.8.3
* MacBook Catalina
* Assembling nanopore reads that were first filtered with Filtlong, then subsampled with Trycycler
* Command used: `flye --nano-raw JB28_trycycler_subsampled/sample_01.fastq --out-dir JB28_flye003 --threads 4`
* Nanopore reads are from a pure bacterial isolate
* Flye log - [flye.log](https://github.com/fenderglass/Flye/files/6226953/flye.log)
* Flye info file - [assembly_info.txt](https://github.com/fenderglass/Flye/files/6226956/assembly_info.txt)

Flye produced two contigs - a large one (the genome), and a small one that represents the 16S rRNA operon for the same bacterium.

I tried using `--meta --keep-haplotypes` as suggested in issue #296, but the result was the same - two contigs. Here's the log: [flye.log](https://github.com/fenderglass/Flye/files/6226951/flye.log)

Assembling the same nanopore reads with Canu and also Minimap/Miniasm/Minipolish002 only gave the single large genome contig.

Do you know why I might be getting the small contig with Flye, and how I might be able to avoid this?

Thanks
Roberto

**Comment by aistBMRG** [comment] 2021-03-30 13:51
Hi, 

Just to follow up on the above, I am also getting extra contigs in my isolate bacterial genome assembly (run using --meta and --plasmids). This is from nanopore sequencing data with an estimated genome coverage of about 140x. The extra contigs are low abundance but just curious as I could consider the main contig as complete, and ignore the others; any suggestions would be helpful. 

#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
**contig_1	2559958	313	Y	N	1	*	1**
contig_4	15693	44	N	N	1	*	*,4,*
contig_2	14712	27	N	N	1	*	*,2,*
contig_6	11328	32	Y	Y	1	12	6
contig_7	10643	31	N	N	1	*	*,7,*
contig_8	8801	41	Y	Y	1	10	8
contig_5	6636	40	N	N	1	*	*,5,*
contig_3	5759	36	Y	Y	1	8	3

Best,

Dieter

**Comment by aistBMRG** [comment] 2021-03-30 14:00
Sorry but just another small question. Another nanopore-based assembly(run using --meta and --plasmids) yielded the following:

#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_1	2424394	482	Y	N	1	*	1
contig_3	169137	523	Y	N	1	*	3
contig_2	7661	34	Y	Y	1	*	2


Now, contig_2 seems to be marked as low coverage. However, looking at the assembly_graph.gfa file, the depth is marked much higher. Would it be possible to clarify; I guess I am misinterpreting a basic thing, maybe related to mult.? 

Fyi, the cov vs depth in the gfa is as follows:
contig_1/edge_1 cov = 482 and depth = 444.0x
contig_2/edge_2 cov = 34 and depth = 1662.0x
contig_3/edge_3 cov = 523 and depth = 476.0x

Thanks again! I always appreciate your help and input.

Regards,

Dieter

**Comment by mikolmogorov** [comment] 2021-04-09 22:04
@ranitori Based on the log, the short edge seems to represent an artifact of repeat resolution and could be safely ignored. It is possible though that this was caused by a heterogeneity in repeat length within the bacterial culture. If you think this could be of interest, you might want to look at read alignments within the regions where the repetitive contig maps.

@aistBMRG similarly, these short contigs with low coverage might represent small assembly artifacts or some real contamination; the large circular contig is likely complete. I would try looking at the gfa visualization to check where the short contigs belong.

Wrt to the graph vs assembly_info coverage - you are right, it is an existing issue that I need to fix. The coverage in assembly_info is after polishing, and therefore is the most up-to-date. The coverage in the assembly_graph is retained from the previous stages of the pipeline.

**Comment by aistBMRG** [comment] 2021-04-10 05:02
Thanks a lot for taking the time to clarify my questions; I'll check the short contigs to assess whether to keep them or not. 

Dieter

**Comment by ranitori** [comment] 2021-04-11 22:25
Thanks for the reply, much appreciated!

**Comment by mikolmogorov** [comment] 2021-04-13 16:31
Marking as resolved, but feel free to follow up here if you have any extra questions.

**Closed as completed by mikolmogorov** 2021-04-13 16:31 UTC
Labels: question
