### ISSUE TITLE
After polishing - super spliting of contigs?

### ISSUE THREAD

**Issue by raw937** [fenderglass/ABruijn#264] opened 2020-05-18 17:18 UTC
Hello, 

I had an assembly go from: 
#draft 
1637 contigs
941620044 size
7459830 N50

#polish 
6181 contigs
696295615 size
1215197 N50

Min contig does from 14,999 to 399 bp.

Any thoughts?

**Comment by mikolmogorov** [comment] 2020-05-20 22:13
Duplicate of #262

**Closed as completed by mikolmogorov** 2020-05-20 22:13 UTC
Labels: question
