### ISSUE TITLE
Stalled on Estimating overlap coverage?

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#479] opened 2022-02-16 04:57 UTC
Hi @fenderglass,

Thanks for your ongoing dedication to the sequencing community. Recently hit an edge case where we had nanopore sequencing data from plasmids with _very_ high depth (>15000X), and for each sample, the assembly got stuck for >90% of the runtime on a single step with a single core: `Estimating overlap coverage`.

This seems to be an edge case of the very high coverage, but unfortunately I did not know it would be this high before assembly and also need `--meta` in case there's multiple plasmids and to recover the short sequences. I'm wondering if there's some kind of heuristic that could be implemented or if this step is amenable to parallelization?

Attaching the log for reference and happy to send data to you if needed: 
[flye_log.txt](https://github.com/fenderglass/Flye/files/8076858/flye_log.txt)

Thanks again!

**Comment by mikolmogorov** [comment] 2022-02-18 20:39
Currently I don't see a good way to approach super high coverage other than downsampling. `--meta` mode is using all available coverage by design (since it's highly variable in metagenomes). You can use `--asm-coverage` to downsample (you'd need a genome size estimate).

Mikhail

**Comment by mikolmogorov** [comment] 2022-03-24 02:56
Marking as resolved  - feel free to follow up if you have more questions.

**Closed as completed by mikolmogorov** 2022-03-24 02:56 UTC
Labels: question

**Comment by schorlton** [comment] 2022-03-24 03:21
Sorry for the delay and thanks for your response/follow up. I don't know the Flye code well enough; in an ideal world you could still use all coverage and either parallelize to estimate overlap coverage or solve another way (eg. approximation) but thanks for your input that no easy solutions at present and all of your work on Flye!

**Comment by mikolmogorov** [comment] 2022-03-31 18:29
@schorlton can you share a dataset that is causing troubles by any chance? You can email at fenderglass@gmail.com

**Comment by schorlton** [comment] 2022-03-31 21:24
Done. Thanks again!!!

**Comment by mikolmogorov** [comment] 2022-04-04 16:20
Thanks, will try to take a look, but can't promise that it will be in the near future.
