### ISSUE TITLE
Expected running time

### ISSUE THREAD

**Issue by rvaser** [fenderglass/ABruijn#238] opened 2020-03-26 17:39 UTC
Dear Mikhail,
I have been running Flye on a plant genome which is around 2 Gbp in size. Flye reached the last step before polishing stage, and is taking some time to finish. It is running on a single thread at this point (I started the program with 96 threads). Is that behavior expected? Can you maybe predict how long it will take until the end?

Thank you and best regards,
Robert

```bash
[2020-03-21 20:24:13] INFO: Aligned read sequence: 115839303647 / 129756343794 (0.892745)
[2020-03-21 20:24:13] INFO: Median overlap divergence: 0.107114
[2020-03-21 20:25:48] INFO: Mean edge coverage: 66
[2020-03-21 20:25:54] INFO: Simplifying the graph
[2020-03-24 10:39:48] INFO: >>>STAGE: contigger
[2020-03-24 10:39:48] INFO: Generating contigs
[2020-03-24 10:39:48] INFO: Reading sequences
[2020-03-24 11:21:37] INFO: Generated 114313 contigs
[2020-03-24 11:30:31] INFO: Added 97 scaffold connections
```

**Comment by mikolmogorov** [comment] 2020-03-26 19:27
Hi Robert,

It's very likely related to this bug: https://github.com/fenderglass/Flye/issues/234

It is now fixed in the latest github code. Feel free to update and use `--resume-from consensus` (or just wait a bit more, it should finish eventually :) ).

Mikhail

**Comment by rvaser** [comment] 2020-03-26 20:36
Thanks for the clarification. Does the time increase with respect to the genome size? I have only a couple of days left on AWS, so I am not sure what to do :D

Edit: Can I resume from contigger stage?

**Comment by mikolmogorov** [comment] 2020-03-26 23:31
It seems like it depends more on the graph complexity, rather than genome size - so it is hard to predict.

Oups - of course, you should use `--resume-from contigger`, not `consensus`!

If the timing is tight, the unpolished contigs are basically ready at `30-contigger/contigs.fasta`. The remaining stages are just polishing and generating scaffolds. But as you see, typically there are not too many scaffold connections, so they do not influence the overall contiguity very much.

**Comment by rvaser** [comment] 2020-03-27 08:09
Just one more question, does the number of contigs remain the same before and after polishing?

**Comment by mikolmogorov** [comment] 2020-03-27 19:00
@rvaser as a part of the full pipeline - it might filter out contigs that ended up with very low read coverage. If you run it standalone - it shouldn't.

**Comment by mikolmogorov** [comment] 2020-03-30 20:56
Closing the thread since the original questions seems to be answered. Feel free to follow up if you have more though!

**Closed as completed by mikolmogorov** 2020-03-30 20:56 UTC
Labels: question

**Comment by rvaser** [comment] 2020-03-30 21:11
That will be all, thank you for your quick response!

**Comment by ginnamon** [comment] 2020-05-06 11:26
Seems the problem is still present in the current version of Flye (built using git resources). While I was assembly E.Coli genome, Flye started with 16 threads and ended after some hours with 2 threads usage (I'm talking about assembly step). Is this normal or is the bug still present?

Thanks for helping.

Matteo

**Comment by mikolmogorov** [comment] 2020-05-06 18:37
@ginnamon can you describe you problem in more detail and provide `flye.log`?

**Comment by ginnamon** [comment] 2020-05-08 23:29
First of all, thanks for the quick answer (and sorry for my delay).
Flye successfully assembles my dataset but during the assembly of disjointing the thread usage drops. In particular, the task starts with 16 threads but when it reaches 90% the number of threads used for the computation gradually drops to 5.

I thought it was a problem related to this issue so I decided to notify it, but if I'm wrong and this is the expected behavior please ignore my comment (and sorry for the warning).

Below I provide you the fraction of flye.log referring to the assembly stage

`[2020-05-08 20:27:02] root: INFO: >>>STAGE: assembly
[2020-05-08 20:27:02] root: INFO: Assembling disjointigs
[2020-05-08 20:27:02] root: DEBUG: -----Begin assembly log------
[2020-05-08 20:27:02] root: DEBUG: Running: flye-modules assemble --reads /home/ubuntu/correction_test/pacbio_test/ecoli_test/ecoli_SRX1155577_global221_minid0_ddfs1/1-consensus/cns_final.fasta --out-asm /home/ubuntu/assembler/flye/flye_ecoli_SRX1155577_global221_minid0_ddfs1_testgithub_1/00-assembly/draft_assembly.fasta --genome-size 4800000 --config /home/ubuntu/Flye/flye/config/bin_cfg/asm_corrected_reads.cfg --log /home/ubuntu/assembler/flye/flye_ecoli_SRX1155577_global221_minid0_ddfs1_testgithub_1/flye.log --threads 16 --min-ovlp 3000 --kmer 17
[2020-05-08 20:27:02] DEBUG: Build date: May  6 2020 09:20:32
[2020-05-08 20:27:02] DEBUG: Total RAM: 61 Gb
[2020-05-08 20:27:02] DEBUG: Available RAM: 61 Gb
[2020-05-08 20:27:02] DEBUG: Total CPUs: 16
[2020-05-08 20:27:02] DEBUG: Loading /home/ubuntu/Flye/flye/config/bin_cfg/asm_corrected_reads.cfg
[2020-05-08 20:27:02] DEBUG: Loading /home/ubuntu/Flye/flye/config/bin_cfg/asm_defaults.cfg
[2020-05-08 20:27:02] DEBUG: 	big_genome_threshold=29000000
[2020-05-08 20:27:02] DEBUG: 	max_coverage_drop_rate=5
[2020-05-08 20:27:02] DEBUG: 	chimera_window=100
[2020-05-08 20:27:02] DEBUG: 	min_reads_in_disjointig=4
[2020-05-08 20:27:02] DEBUG: 	max_inner_reads=10
[2020-05-08 20:27:02] DEBUG: 	max_inner_fraction=0.25
[2020-05-08 20:27:02] DEBUG: 	max_separation=500
[2020-05-08 20:27:02] DEBUG: 	unique_edge_length=50000
[2020-05-08 20:27:02] DEBUG: 	min_repeat_res_support=0.51
[2020-05-08 20:27:02] DEBUG: 	out_paths_ratio=5
[2020-05-08 20:27:02] DEBUG: 	graph_cov_drop_rate=5
[2020-05-08 20:27:02] DEBUG: 	coverage_estimate_window=100
[2020-05-08 20:27:02] DEBUG: 	max_bubble_length=50000
[2020-05-08 20:27:02] DEBUG: 	loop_coverage_rate=1.5
[2020-05-08 20:27:02] DEBUG: 	repeat_edge_cov_mult=1.75
[2020-05-08 20:27:02] DEBUG: 	weak_detach_rate=5
[2020-05-08 20:27:02] DEBUG: 	tip_coverage_rate=2
[2020-05-08 20:27:02] DEBUG: 	tip_length_rate=2
[2020-05-08 20:27:02] DEBUG: 	low_cutoff_warning=0
[2020-05-08 20:27:02] DEBUG: 	hard_min_coverage_rate=50
[2020-05-08 20:27:02] DEBUG: 	assemble_kmer_sample=2
[2020-05-08 20:27:02] DEBUG: 	repeat_graph_kmer_sample=2
[2020-05-08 20:27:02] DEBUG: 	read_align_kmer_sample=2
[2020-05-08 20:27:02] DEBUG: 	meta_read_top_kmer_rate=0.75
[2020-05-08 20:27:02] DEBUG: 	meta_read_filter_kmer_freq=50
[2020-05-08 20:27:02] DEBUG: 	maximum_jump=1500
[2020-05-08 20:27:02] DEBUG: 	maximum_overhang=500
[2020-05-08 20:27:02] DEBUG: 	repeat_kmer_rate=100
[2020-05-08 20:27:02] DEBUG: 	assemble_ovlp_relative_divergence=0.03
[2020-05-08 20:27:02] DEBUG: 	repeat_graph_ovlp_divergence=0.03
[2020-05-08 20:27:02] DEBUG: 	read_align_ovlp_divergence=0.03
[2020-05-08 20:27:02] DEBUG: 	add_unassembled_reads=0
[2020-05-08 20:27:02] DEBUG: 	extend_contigs_with_repeats=1
[2020-05-08 20:27:02] DEBUG: 	min_read_cov_cutoff=3
[2020-05-08 20:27:02] DEBUG: 	short_tip_length=10000
[2020-05-08 20:27:02] DEBUG: 	long_tip_length=100000
[2020-05-08 20:27:02] DEBUG: Running with k-mer size: 17
[2020-05-08 20:27:02] DEBUG: Running with minimum overlap 3000
[2020-05-08 20:27:02] DEBUG: Metagenome mode: N
[2020-05-08 20:27:02] INFO: Reading sequences
[2020-05-08 20:27:05] DEBUG: Building positional index
[2020-05-08 20:27:05] DEBUG: Total sequence: 518087710 bp
[2020-05-08 20:27:05] DEBUG: Expected read coverage: 107
[2020-05-08 20:27:05] INFO: Generating solid k-mer index
[2020-05-08 20:27:05] DEBUG: Hard threshold set to 2
[2020-05-08 20:27:05] DEBUG: Started k-mer counting
[2020-05-08 20:27:35] INFO: Counting k-mers (1/2):
[2020-05-08 20:27:38] INFO: Counting k-mers (2/2):
[2020-05-08 20:27:49] DEBUG: Estimated minimum kmer coverage: 25
[2020-05-08 20:27:49] DEBUG: Filtered 8851769 erroneous k-mers
[2020-05-08 20:27:49] DEBUG: Repetitive k-mer frequency: 4013
[2020-05-08 20:27:49] DEBUG: Filtered 150 repetitive k-mers (3.09502e-05)
[2020-05-08 20:27:49] INFO: Filling index table
[2020-05-08 20:27:49] DEBUG: Sampling rate: 2
[2020-05-08 20:27:49] DEBUG: Solid k-mers: 4846352
[2020-05-08 20:27:49] DEBUG: K-mer index size: 190290871
[2020-05-08 20:27:49] DEBUG: Mean k-mer frequency: 39.2648
[2020-05-08 20:27:59] DEBUG: Sorting k-mer index
[2020-05-08 20:28:01] DEBUG: Peak RAM usage: 1 Gb
[2020-05-08 20:28:01] DEBUG: Estimating k-mer identity bias
[2020-05-08 20:29:30] DEBUG: Median overlap divergence: 0.0378709
[2020-05-08 20:29:30] DEBUG: K-mer estimate bias (true - est): 0.01194
[2020-05-08 20:29:30] DEBUG: Max divergence threshold set to 0.0678709
[2020-05-08 20:29:30] INFO: Extending reads
[2020-05-08 20:29:30] DEBUG: Estimating overlap coverage
[2020-05-08 20:30:22] INFO: Overlap-based coverage: 50
[2020-05-08 20:30:22] INFO: Median overlap divergence: 0.0314217
[2020-05-08 20:30:22] DEBUG: Sequence divergence distribution: 

    |    *        |                                                                                      
    |    *        |                                                                                      
    |    *        |                                                                                      
    |    *        |                                                                                      
    |    *        |                                                                                      
    |   ***       |                                                                                      
    |   ***       |                                                                                      
    |   ***       |                                                                                      
    |   ***       |                                                                                      
    |   ***       |                                                                                      
    |   ****      |                                                                                      
    |   ****      |                                                                                      
    |   *****     |                                                                                      
    |   *****     |                                                                                      
    |   ******    |                                                                                      
    |   ********  |                                                                                      
    |   ******** **                                                                                      
    |   ************                                                                                     
    |   ***************                                                                                  
    |  ********************* *        *  ** *     ** **  *** **  **   * *   *                            
    ----------------------------------------------------------------------------------------------------
    0%        5%        10%       15%       20%       25%       30%       35%       40%       45%       

    Q25 = 0.023, Q50 = 0.031, Q75 = 0.05

[2020-05-08 20:31:20] DEBUG: Assembled disjointig 1
	With 1038 reads
	Start read: +SRR2829967.1.75942
	At position: 420
	leftTip: 0 rightTip: 0
	Suspicious: 1
	Mean extensions: 20
	Avg overlap len: 8440
	Min overlap len: 3302
	Inner reads: 0
	Length: 3036290
[2020-05-08 20:31:20] DEBUG: Ovlp index size: 369584
[2020-05-08 20:31:20] DEBUG: Inner: 73292 covered: 77368 total: 157494
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1032 reads and 1030 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1185 reads and 450 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1188 reads and 450 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1756 reads and 1024 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1759 reads and 1024 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1759 reads and 1024 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1036 reads and 1034 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 478 reads and 476 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1756 reads and 1022 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 818 reads and 815 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 632 reads and 630 inner overlaps
[2020-05-08 20:31:20] DEBUG: Discarded disjointig with 1760 reads and 1022 inner overlaps
[2020-05-08 20:31:21] DEBUG: Assembled disjointig 2
	With 733 reads
	Start read: +SRR2721739.1.140744
	At position: 608
	leftTip: 0 rightTip: 0
	Suspicious: 0
	Mean extensions: 20
	Avg overlap len: 8349
	Min overlap len: 3708
	Inner reads: 0
	Length: 2175199
[2020-05-08 20:31:21] DEBUG: Ovlp index size: 372667
[2020-05-08 20:31:21] DEBUG: Inner: 125328 covered: 131822 total: 157494
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 735 reads and 733 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 430 reads and 428 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 4 reads and 2 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 636 reads and 634 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 79 reads and 77 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 6 reads and 4 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 4 reads and 2 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 519 reads and 517 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 207 reads and 205 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 582 reads and 580 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 5 reads and 3 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 547 reads and 545 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 98 reads and 96 inner overlaps
[2020-05-08 20:31:21] DEBUG: Discarded disjointig with 1073 reads and 1069 inner overlaps
[2020-05-08 20:31:22] DEBUG: Assembled disjointig 3
	With 10 reads
	Start read: +SRR2721739.1.55504
	At position: 4
	leftTip: 1 rightTip: 1
	Suspicious: 2
	Mean extensions: 10
	Avg overlap len: 5847
	Min overlap len: 3067
	Inner reads: 0
	Length: 41367
[2020-05-08 20:31:22] DEBUG: Ovlp index size: 381825
[2020-05-08 20:31:22] DEBUG: Inner: 125692 covered: 132406 total: 157494
[2020-05-08 20:31:22] DEBUG: Discarded disjointig with 10 reads and 8 inner overlaps
[2020-05-08 20:31:22] DEBUG: Assembled disjointig 4
	With 21 reads
	Start read: +SRR2829967.1.86837
	At position: 3
	leftTip: 1 rightTip: 1
	Suspicious: 2
	Mean extensions: 11
	Avg overlap len: 7269
	Min overlap len: 3445
	Inner reads: 0
	Length: 72089
[2020-05-08 20:31:22] DEBUG: Ovlp index size: 383713
[2020-05-08 20:31:22] DEBUG: Inner: 127048 covered: 133980 total: 157494
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 15 reads and 4 inner overlaps
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 12 reads and 10 inner overlaps
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 19 reads and 17 inner overlaps
[2020-05-08 20:31:23] DEBUG: Assembled disjointig 5
	With 15 reads
	Start read: +SRR2721739.1.15493
	At position: 9
	leftTip: 0 rightTip: 0
	Suspicious: 0
	Mean extensions: 14
	Avg overlap len: 6896
	Min overlap len: 3786
	Inner reads: 0
	Length: 54939
[2020-05-08 20:31:23] DEBUG: Ovlp index size: 385308
[2020-05-08 20:31:23] DEBUG: Inner: 127588 covered: 134484 total: 157494
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 23 reads and 17 inner overlaps
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 22 reads and 20 inner overlaps
[2020-05-08 20:31:23] DEBUG: Discarded disjointig with 21 reads and 19 inner overlaps
[2020-05-08 20:31:24] DEBUG: Assembled disjointig 6
	With 20 reads
	Start read: +SRR2829967.1.136079
	At position: 19
	leftTip: 1 rightTip: 1
	Suspicious: 4
	Mean extensions: 6
	Avg overlap len: 5051
	Min overlap len: 3090
	Inner reads: 0
	Length: 70666
[2020-05-08 20:31:24] DEBUG: Ovlp index size: 386376
[2020-05-08 20:31:24] DEBUG: Inner: 128244 covered: 135314 total: 157494
[2020-05-08 20:31:24] DEBUG: Discarded disjointig with 16 reads and 14 inner overlaps
[2020-05-08 20:31:24] DEBUG: Discarded disjointig with 17 reads and 15 inner overlaps
[2020-05-08 20:31:25] DEBUG: Assembled disjointig 7
	With 9 reads
	Start read: +SRR2721739.1.38260
	At position: 6
	leftTip: 1 rightTip: 1
	Suspicious: 4
	Mean extensions: 8
	Avg overlap len: 5719
	Min overlap len: 3346
	Inner reads: 0
	Length: 40626
[2020-05-08 20:31:25] DEBUG: Ovlp index size: 387777
[2020-05-08 20:31:25] DEBUG: Inner: 128504 covered: 135724 total: 157494
[2020-05-08 20:31:25] DEBUG: Discarded disjointig with 6 reads and 4 inner overlaps
[2020-05-08 20:31:27] DEBUG: Assembled disjointig 8
	With 7 reads
	Start read: +SRR2829966.1.131746
	At position: 5
	leftTip: 0 rightTip: 0
	Suspicious: 0
	Mean extensions: 10
	Avg overlap len: 6097
	Min overlap len: 5833
	Inner reads: 0
	Length: 21010
[2020-05-08 20:31:27] DEBUG: Ovlp index size: 388196
[2020-05-08 20:31:27] DEBUG: Inner: 128572 covered: 135944 total: 157494
[2020-05-08 20:31:30] DEBUG: Assembled disjointig 9
	With 6 reads
	Start read: +SRR2829967.1.157554
	At position: 4
	leftTip: 1 rightTip: 0
	Suspicious: 2
	Mean extensions: 8
	Avg overlap len: 5351
	Min overlap len: 4393
	Inner reads: 0
	Length: 30357
[2020-05-08 20:31:30] DEBUG: Ovlp index size: 388509
[2020-05-08 20:31:30] DEBUG: Inner: 128690 covered: 136354 total: 157494
[2020-05-08 20:31:30] DEBUG: Discarded disjointig with 7 reads and 5 inner overlaps
[2020-05-08 22:38:30] DEBUG: Assembled disjointig 10
	With 4 reads
	Start read: +SRR2829967.1.157664
	At position: 3
	leftTip: 0 rightTip: 0
	Suspicious: 0
	Mean extensions: 8
	Avg overlap len: 14120
	Min overlap len: 7883
	Inner reads: 0
	Length: 35840
[2020-05-08 22:38:30] DEBUG: Ovlp index size: 390256
[2020-05-08 22:38:30] DEBUG: Inner: 128704 covered: 157494 total: 157494
[2020-05-08 22:38:50] INFO: Assembled 10 disjointigs
[2020-05-08 22:38:50] INFO: Generating sequence
[2020-05-08 22:39:16] DEBUG: Writing FASTA
[2020-05-08 22:39:16] DEBUG: Peak RAM usage: 4 Gb
-----------End assembly log------------`

**Comment by mikolmogorov** [comment] 2020-05-10 05:27
@ginnamon ok, thanks for getting back!
