### ISSUE TITLE
error towards last step

### ISSUE THREAD

**Issue by rob123king** [fenderglass/ABruijn#221] opened 2020-02-14 10:02 UTC
[2020-02-12 19:00:21] INFO: Running minimap2
[2020-02-13 08:24:42] INFO: Separating alignment into bubbles
[2020-02-13 11:10:38] INFO: Alignment error rate: 0.138915
[2020-02-13 11:10:38] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2020-02-13 19:29:43] INFO: Polishing genome (2/2)
[2020-02-13 19:30:21] INFO: Running minimap2
[2020-02-13 23:09:10] ERROR: Command '['flye-minimap2', '/home/data/pest_genomics/species/smrt1and2_7000/40-polishing/chunks_2.fasta', '/home/data/pest_genomics/species/bothcellsNez.fastq', '-x', 'map-pb', '-t', '60', '-a', '-p', '0.5', '-N', '10']' returned non-zero exit status -11

Did the first polishing step but failed on the second. I'l try resuming but it will start the polishing part all over again. rather start from 2nd polish onwards

**Comment by mikolmogorov** [comment] 2020-02-18 21:00
Looks like duplicate of #152, probably a rare bug in minimap2. See the original issue for the discussion.

**Closed as completed by mikolmogorov** 2020-02-18 21:00 UTC
Labels: duplicate
