### ISSUE TITLE
Error during Stage 2 - Consensus, minimap2 alignment

### ISSUE THREAD

**Issue by alelim-bio** [fenderglass/ABruijn#228] opened 2020-03-03 18:57 UTC
Hello,

I was hoping to receive some advice on an issue I was having during the minimap2 alignment of the consensus stage. 

Some background information, I am currently working on a genome assembly of a ~17G with a limited amount of genome coverage ~10-15 using raw oxford nanopore reads. For pre-processing, I have used prinseq to remove any duplicates in the .fasta file. Lastly, some hardware specifications, I am using a 3 TB memory node with plenty of hard drive space and a CPU with 64 threads. 

 Currently, the flye.log file shows

 `-----------End assembly log------------
[2020-03-01 04:13:15] root: DEBUG: Disjointigs length: 26287839216, N50: 165320
[2020-03-01 04:13:15] root: INFO: >>>STAGE: consensus
[2020-03-01 04:20:05] root: INFO: Running Minimap2
[2020-03-01 18:48:24] root: ERROR: Command '['flye-minimap2', '/pylon5/mc5fr6p/alelim/ACTIVE_ANALYSIS/duster/flye_assembly/10-consensus/chunks.fasta', 'prinseqPP_nodup_combined_duster_basecalled_reads.fasta', '-x', 'map-ont', '-t', '64', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status 1.
`
In order to evaluate if this error was a one-time problem I attempted to resume the flye assembly and have received the same error. I did notice that the first attempt stopped at an alignment file size of 700G and the second attempt stopped at 331G.

Thank you for your time!

Kind Regards,

Alex Lim

PS. I have attached the flye.log just in case and apologies if this was already resolved in a previous issue post, I was unable to find the solution while perusing the previous posts.

[flye_first_run.zip](https://github.com/fenderglass/Flye/files/4283046/flye_first_run.zip)

**Comment by mikolmogorov** [comment] 2020-03-04 20:49
Duplicate of #213

**Comment by mikolmogorov** [comment] 2020-03-04 20:50
Please follow the advice from #213, in particular try the newest release (you can add `--resume-from consensus` to save time). Please post any follow-ups to #213.

**Closed as completed by mikolmogorov** 2020-03-04 20:50 UTC
