### ISSUE TITLE
Pipeline silently fails if there are spaces in the read paths

### ISSUE THREAD

**Issue by DavideGue** [fenderglass/ABruijn#320] opened 2020-11-25 13:22 UTC
Hello,
I'm trying to run flye to assemble  a region of 100kb using long reads in fastq format obtained from ONT MinION instrument and I got the following error message:

[2020-11-24 18:56:07] INFO: >>>STAGE: consensus
[2020-11-24 18:56:08] INFO: Running Minimap2
[2020-11-24 18:56:10] INFO: Computing consensus
[2020-11-24 18:56:11] INFO: Alignment error rate: 0.000000
[2020-11-24 18:56:11] INFO: >>>STAGE: repeat
[2020-11-24 18:56:11] INFO: Building and resolving repeat graph
[2020-11-24 18:56:11] INFO: Parsing disjointigs
[2020-11-24 18:56:11] ERROR: parse error in /home/davide/Scrivania/Project_Folder_SO100268/10-consensus/consensus.fasta on line 1: empty sequence
[2020-11-24 18:56:11] ERROR: Command '['flye-modules', 'repeat', '--disjointigs', '/home/davide/Scrivania/Project_Folder_SO100268/10-consensus/consensus.fasta', '--reads', '/home/davide/Scrivania/Project_Folder_SO100268/ONT data Folder/FASTQ data/5-Morex/barcode11.run1.run2.merged.fastq.gz', '--out-dir', '/home/davide/Scrivania/Project_Folder_SO100268/20-repeat', '--config', '/home/davide/Programmi/Flye/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/home/davide/Scrivania/Project_Folder_SO100268/flye.log', '--threads', '4', '--keep-haplotypes', '--min-ovlp', '2000']' returned non-zero exit status 1
[2020-11-24 18:56:11] ERROR: Pipeline aborted

Then I converted fastq files into fasta removing the @ in the sequences header and I re-ran the command and, again I obtained the same error message.
the command I ran is as follows:
python bin/flye --nano-raw /home/davide/Scrivania/Project_Folder_SO100268/ONT\ data\ Folder/FASTQ\ data/5-Morex/barcode11.run1.run2.merged.fastq.gz --out-dir /home/davide/Scrivania/Project_Folder_SO100268/ --threads 4 --keep-haplotypes -g 0.2m
flye created three folders named: 00-assembly containing the draft_assembly.fasta file containing 2615 disjointigs;
10-consensus containing a chunk.fasta.fai index and an empty consensus.fasta file and finally a third empty folder named 20-repeat.
So I cannot figure out wat is going wrong. Can I have some suggestions?
Thank in advance
Davide

**Comment by mikolmogorov** [comment] 2020-11-30 19:55
@DavideGue 

Could you please post the full `flye.log`, and also provide the ouput of `zcat barcode11.run1.run2.merged.fastq.gz | head`?

Mikhail

**Comment by DavideGue** [comment] 2020-12-01 06:59
Hi @fenderglass,
thanks for your answer.
Here the first ten lines of zcat command
[zcat_10lines.txt](https://github.com/fenderglass/Flye/files/5620739/zcat_10lines.txt)
and here the complete flye.log file
[flye.log](https://github.com/fenderglass/Flye/files/5620748/flye.log)

**Comment by mikolmogorov** [comment] 2020-12-03 02:57
@DavideGue thanks for sharing the logs. Indeed looks like some disjointigs were assembled, but then the consensus module failed to generate any sequence. Any chance you can share the data so I can reproduce the issue? Feel free to email me at fenderglass@gmail.com.

Mikhail

**Comment by mikolmogorov** [comment] 2020-12-12 02:06
@DavideGue 

Thanks for sending the data - I was able to generate the assembly from these reads. Looks like the problem was that you had spaces in the path to input reads, which were incorrectly handled during the minimap2 call. It should work if you remove spaces from directory names or move the file. I will add an extra check for that in the next Flye version.

Mikhail

**Closed as completed by mikolmogorov** 2020-12-12 02:06 UTC
Labels: crash, more info needed

**Comment by DavideGue** [comment] 2020-12-14 11:40
Dear Mikhail,
thank you for solving the issue.
Following your suggestions I was able to finish a run and obtain an assembly.
I haev a further question if you have time to answer it:
the sequenced region should be about 100kb long (it is a targeted resequencing), however it seems that the unique scaffold outputted by flye is 25777 bp long.
Do you have any idea about this?
Thanks in advance
Best whishes
Davide





[cid:e2a884ea-5b96-4733-9d2f-9d4f2ef7b5b9]<https://www.crea.gov.it>

---------------------------------------------------------

Davide Guerra, Ph.D

CREA-GB - Research Centre for Genomics and Bioinformatics

Via San Protaso, 302

Fiorenzuola d'Arda PC, 29017, Italy

Phone number 0523 983 758



INFORMATIVA PRIVACY (Reg.UE 2016/679 E d.Lgs.196/2003)

Questa email ed i suoi eventuali allegati sono da considerarsi materiale riservato e di proprietà della scrivente ente.

Nel caso venisse ricevuta per errore non deve essere divulgata, copiata o distribuita per alcuna ragione.

Le comunicazioni che transitano attraverso il presente indirizzo di posta elettronica hanno carattere e finalità prettamente lavorative, pertanto potranno essere conosciute all’interno dell’organizzazione aziendale.

Qualsiasi dato personale sarà comunque trattato in conformità alle vigenti normative in materia di privacy e protezione dei dati personali. A tale riguardo potete esercitare tutti i diritti previsti dalla legge semplicemente rispondendo alla presente ed esplicitando la vostra richiesta. Maggiori info in materia di privacy: https://www.crea.gov.it/home



PRIVACY INFORMATION (Reg. UE 2016/679 E d.Lgs.196 / 2003)

This e-mail and its possible attachments are to be considered as confidential material and property of the undersigned company.

Should it be received by mistake it should not be disclosed, copied or distributed for any reason.

The communications that transit through this e-mail address are purely for business purposes and therefore can be known within the company organization.

Any personal data will in any case be processed in compliance with current regulations regarding privacy and personal data protection.

In this regard, you can exercise all the rights provided by law by simply replying to this and making your request explicit. More info on privacy: https://www.crea.gov.it/home

________________________________
Da: Mikhail Kolmogorov <notifications@github.com>
Inviato: sabato 12 dicembre 2020 03:06
A: fenderglass/Flye <Flye@noreply.github.com>
Cc: davide.guerra <davide.guerra@crea.gov.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [fenderglass/Flye] Consensus stage failure (#320)


@DavideGue<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDavideGue&data=04%7C01%7Cdavide.guerra%40crea.gov.it%7C4d3d40c45a4b47de083f08d89e4283ea%7Cd59c04b9bde247f7b1b80be26a568618%7C0%7C0%7C637433355817152686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oAWDxMHOPaWX%2BFUG3QIfDMfBOfvv9nEBnY%2BR%2B5RZi9A%3D&reserved=0>

Thanks for sending the data - I was able to generate the assembly from these reads. Looks like the problem was that you had spaces in the path to input reads, which were incorrectly handled during the minimap2 call. It should work if you remove spaces from directory names or move the file. I will add an extra check for that in the next Flye version.

Mikhail

**Comment by mikolmogorov** [comment] 2020-12-16 04:18
@DavideGue hard to tell without extra information about the sequencing protocol. Could be due to gaps in coverage or highly uneven coverage. I would try the metagenome mode if you have not yet. I believe that Flye should have output more than a single sequence - is it possible that the regions is fragmented?

**Comment by DavideGue** [comment] 2020-12-16 14:13
Hi Mikhail,
thank you again for the answer and for your time.
Yes, you are right. Flye produced several fragments (containing my gene of interest), the longest fragment is the scaffold  (25kb long) but there are others shorter altough I used ONT MinION.
For sure I will try the metagenome mode.
Cheers
Davide





[cid:454b3a86-4eb7-4e58-9cdd-dcc74a45d137]<https://www.crea.gov.it>

---------------------------------------------------------

Davide Guerra, Ph.D

CREA-GB - Research Centre for Genomics and Bioinformatics

Via San Protaso, 302

Fiorenzuola d'Arda PC, 29017, Italy

Phone number 0523 983 758



INFORMATIVA PRIVACY (Reg.UE 2016/679 E d.Lgs.196/2003)

Questa email ed i suoi eventuali allegati sono da considerarsi materiale riservato e di proprietà della scrivente ente.

Nel caso venisse ricevuta per errore non deve essere divulgata, copiata o distribuita per alcuna ragione.

Le comunicazioni che transitano attraverso il presente indirizzo di posta elettronica hanno carattere e finalità prettamente lavorative, pertanto potranno essere conosciute all’interno dell’organizzazione aziendale.

Qualsiasi dato personale sarà comunque trattato in conformità alle vigenti normative in materia di privacy e protezione dei dati personali. A tale riguardo potete esercitare tutti i diritti previsti dalla legge semplicemente rispondendo alla presente ed esplicitando la vostra richiesta. Maggiori info in materia di privacy: https://www.crea.gov.it/home



PRIVACY INFORMATION (Reg. UE 2016/679 E d.Lgs.196 / 2003)

This e-mail and its possible attachments are to be considered as confidential material and property of the undersigned company.

Should it be received by mistake it should not be disclosed, copied or distributed for any reason.

The communications that transit through this e-mail address are purely for business purposes and therefore can be known within the company organization.

Any personal data will in any case be processed in compliance with current regulations regarding privacy and personal data protection.

In this regard, you can exercise all the rights provided by law by simply replying to this and making your request explicit. More info on privacy: https://www.crea.gov.it/home

________________________________
Da: Mikhail Kolmogorov <notifications@github.com>
Inviato: mercoledì 16 dicembre 2020 05:18
A: fenderglass/Flye <Flye@noreply.github.com>
Cc: davide.guerra <davide.guerra@crea.gov.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [fenderglass/Flye] Pipeline silently fails if there are spaces in the read paths (#320)


@DavideGue<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDavideGue&data=04%7C01%7Cdavide.guerra%40crea.gov.it%7C651acf37a0b342c8d13e08d8a179abca%7Cd59c04b9bde247f7b1b80be26a568618%7C0%7C0%7C637436891247507213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Axcxj0amyl7%2B%2FdIHRUPdLkXI%2FJ5qm2%2BAcK0P9JJJFTc%3D&reserved=0> hard to tell without extra information about the sequencing protocol. Could be due to gaps in coverage or highly uneven coverage. I would try the metagenome mode if you have not yet. I believe that Flye should have output more than a single sequence - is it possible that the regions is fragmented?
