### ISSUE TITLE
Flye --meta taking very long time to assemble my reads

### ISSUE THREAD

**Issue by gregmcc97** [fenderglass/ABruijn#614] opened 2023-07-12 09:46 UTC
Hi, 

I am trying to assemble some metagenomes from a faecal sample that was deeply sequenced using ONT PromethION. 

**The problem is they are taking a very long time to assemble.** I have just had to stop an assembly that has been running for nearly 2 months (since 16th May), and it hadn't got the first checkpoint yet. It had been stuck at 80% on the disjontig assembly step (at the median overlap divergence bit) for a month. This is the same for all 4 of my samples - they are all taking ages.

Sample H3 that I just had to stop has 22,183,447 reads with 83,353,696,127 total bases (the rest of my samples are all similar). The command I was running was:

`flye --nano-hq reads/H3_long_filt_hr.fastq.gz -o flye_H3 -t 46 --meta`

**Do you know why this would take so long to assemble?** It had had over 60,000 hours CPU time and hadn't finished the assembly stage yet. The assembly size I'm expecting is between 0.7-1 Gb. On the benchmarks table it says a sheep gut metagenome assembly took around 3500 h CPU time to assemble so I think something must be going wrong for my samples?

I have attached the [flye.log](https://github.com/fenderglass/Flye/files/12026375/flye.log) file for this assembly that I ended - please let me know if you need any other information. 

Also I have 94 CPUs available so can rerun using all of those, but I have tried that before and it was still taking over a month so I had to cancel it. 

Thank you very much.

**Comment by mikolmogorov** [comment] 2023-07-24 13:54
Hi,

Sorry for my late response! 

Metagenomes are tricky and performance could vary a lot for different samples. The sheep gut metagenome was sequenced with HiFi and reads were size selected more aggressively, this may be why yours is taking so much longer. Another key thing is composition - based on the log, I see that you likely have one or a few species with very high sequencing depth, and a long tail of low-depth species. This is basically worst-case scenario.. A few suggestions though:

1. First, is it R10 data? You can try adding `--read-error 0.03 --extra-params minimizer_window=10`.
2. You can also try manually increasing minimum overlap size to either 3000 (`-m 3000`) or 5000.
3. But ultimately, I think the issue is very high depth. I would try to downsample (maybe take 10% of reads for the first iteration). This should still assemble bacteria with high abundance and give you an idea of coverage distributions. From there, if you want to reconstruct underrepresented species, you may try to map all original reads to your assembly, and remove the reads that map in full against the downsampled contigs.

**Comment by Ge0rges** [comment] 2023-08-25 20:01
@fenderglass are those `--read-error 0.03 --extra-params minimizer_window=10` parameters recommended for any metagenomic workflow using Nanopore R10 data?

**Comment by mikolmogorov** [comment] 2023-08-28 13:31
@Ge0rges I have not seen too many R10 metagenomic datasets yet, so hard to generalize. I'd give it a try!

**Comment by Ge0rges** [comment] 2023-08-29 01:41
Thanks for the tip @fenderglass any recommendations as to how to objectively evaluate the assemblies that come out of Flye with and without those parameters? This is my first metagenomic analysis :)

**Comment by mikolmogorov** [comment] 2023-09-05 15:23
@Ge0rges there are many methods and layers of complexity, so hard to give a short answer. I suggest reading metaFlye and hifiasm-meta papers, they have a lot of various evaluations that should be helpful.

**Comment by mikolmogorov** [comment] 2023-10-12 20:48
Marking as resolved, but feel free to follow up if you have more questions!

**Closed as completed by mikolmogorov** 2023-10-12 20:48 UTC
Labels: question
