### ISSUE TITLE
core dump from polishing stage

### ISSUE THREAD

**Issue by intikhab** [fenderglass/ABruijn#153] opened 2019-09-13 10:44 UTC
Hi,

One of my run on assembling a plant genome PacBio data failed with a core dump. gbd core file reports the following:
BFD: Warning: /ibex/scratch/projects/c2022/Data/Interm/Assemblies/PacBio_Sequel_UGT_BCL/PacBio_Sequel_UGT_BCL_IBL/flye/core.65328 is truncated: expected core file size >= 40372023296, found: 13013045248.
BFD: Warning: /ibex/scratch/projects/c2022/Data/Interm/Assemblies/PacBio_Sequel_UGT_BCL/PacBio_Sequel_UGT_BCL_IBL/flye/core.65328 is truncated: expected core file size >= 40372023296, found: 13013045248.
[New LWP 42449]
[New LWP 42450]
[New LWP 42451]
[New LWP 42454]
[New LWP 42392]
[New LWP 42393]
[New LWP 42452]
[New LWP 42404]
[New LWP 42455]
[New LWP 42398]
[New LWP 42400]
[New LWP 42395]
[New LWP 42407]
[New LWP 42402]
[New LWP 42396]
[New LWP 42394]
[New LWP 65328]
[New LWP 42403]
[New LWP 42405]
[New LWP 42399]
[New LWP 42406]
[New LWP 42411]
[New LWP 42401]
[New LWP 42409]
[New LWP 42408]
[New LWP 42413]
[New LWP 42412]
[New LWP 42415]
[New LWP 42410]
[New LWP 42397]
[New LWP 42417]
[New LWP 42419]
[New LWP 41551]
[New LWP 42416]
[New LWP 42421]
[New LWP 42423]
[New LWP 42430]
[New LWP 42414]
[New LWP 42428]
[New LWP 42420]
[New LWP 42431]
[New LWP 42422]
[New LWP 42427]
[New LWP 42436]
[New LWP 42424]
[New LWP 42425]
[New LWP 42437]
[New LWP 42429]
[New LWP 42426]
[New LWP 42438]
[New LWP 42433]
[New LWP 42441]
[New LWP 42439]
[New LWP 42442]
[New LWP 42435]
[New LWP 42440]
[New LWP 42443]
[New LWP 42444]
[New LWP 42446]
[New LWP 42447]
[New LWP 42445]
[New LWP 42434]
[New LWP 41552]
[New LWP 42418]
[New LWP 42432]
[New LWP 42448]
[New LWP 42453]
Failed to read a valid object file image from memory.
Core was generated by `flye-minimap2 /ibex/scratch/projects/c2022/Data/Interm/Assemblies/PacBio_Sequel'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000041c21a in ?? ()
??

It happened once before and I resumed the assembly ending up again with a core dump.

Is it related to memory? This assembly was running on a 1Tb node, with options -c 32 -g 2.5g --asm-coverage 50

Tail of the log is as follows:
[2019-09-12 10:27:01] root: INFO: Resuming previous run
[2019-09-12 10:27:01] root: INFO: >>>STAGE: polishing
[2019-09-12 10:27:01] root: INFO: Polishing genome (1/1)
[2019-09-12 10:27:37] root: INFO: Running minimap2
[2019-09-12 18:26:46] root: ERROR: Command '['flye-minimap2', .... , '-x', 'map-pb', '-t', '64', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status -11

Any help to rescue this assembly from this problem?

Intikhab

**Comment by mikolmogorov** [comment] 2019-09-16 18:16
Hi Intikhab,

Should not be the memory issue, but might be a problem with minimap2. Could you please:
1. Send me the full `flye.log` file.
2. Try to run minimap2 command manually (remove quotation marks): `flye-minimap2', .... , '-x', 'map-pb', '-t', '64', '-a', '-p', '0.7', '-N', '10` to see if it outputs more informative error. 

Mikhail

**Comment by mikolmogorov** [comment] 2019-10-14 16:15
Duplicate of #152, please continue discussion there.

**Closed as completed by mikolmogorov** 2019-10-14 16:15 UTC
Labels: bug
