### ISSUE TITLE
Error in the polishing stage

### ISSUE THREAD

**Issue by hidvegin** [fenderglass/ABruijn#593] opened 2023-04-13 07:44 UTC
I would like to assemble 4 Gb diploid genome from PacBio raw reads. 

I used this script for run `flye`:

`singularity exec /home/fk8jybr/singularity_images/flye.2.9.1.simg flye --resume --pacbio-raw /home/fk8jybr/LC001pacbio.fastq.gz --out-dir /home/fk8jybr/output/Flye/ --genome-size 4g --threads 80`

I got the error in the polishing stage:

```
[2023-04-12 10:25:36] root: INFO: >>>STAGE: polishing
[2023-04-12 10:25:36] root: INFO: Polishing genome (1/1)
[2023-04-12 10:25:36] root: INFO: Running minimap2
[2023-04-12 16:58:18] root: INFO: Separating alignment into bubbles
[2023-04-12 17:34:03] root: DEBUG: Generated 27693206 bubbles
[2023-04-12 17:34:03] root: DEBUG: Split 18469 long bubbles
[2023-04-12 17:34:03] root: DEBUG: Skipped 6507 empty bubbles
[2023-04-12 17:34:03] root: DEBUG: Skipped 260 bubbles with long branches
[2023-04-12 17:34:03] root: INFO: Alignment error rate: 0.159854
[2023-04-12 17:34:03] root: INFO: Correcting bubbles
[2023-04-12 18:01:56] root: ERROR: Command '['flye-modules', 'polisher', '--bubbles', '/home/fk8jybr/output/Flye/40-polishing/bubbles_1.fasta$
[2023-04-12 18:01:56] root: ERROR: Pipeline aborted
[2023-04-12 21:03:32] root: INFO: Starting Flye 2.9.1-b1780
[2023-04-12 21:03:32] root: DEBUG: Cmd: /usr/local/bin/flye --resume --pacbio-raw /home/fk8jybr/LC001pacbio.fastq.gz --out-dir /home/fk8jybr/$
[2023-04-12 21:03:32] root: DEBUG: Python version: 2.7.17 (default, Jul  1 2022, 15:56:32)
[GCC 7.5.0]
[2023-04-12 21:03:32] root: INFO: Resuming previous run
[2023-04-12 21:03:33] root: INFO: >>>STAGE: polishing
[2023-04-12 21:03:33] root: INFO: Polishing genome (1/1)
[2023-04-12 21:03:33] root: INFO: Running minimap2
[2023-04-13 04:08:12] root: INFO: Separating alignment into bubbles
[2023-04-13 04:35:19] root: DEBUG: Generated 27693206 bubbles
[2023-04-13 04:35:19] root: DEBUG: Split 18469 long bubbles
[2023-04-13 04:35:19] root: DEBUG: Skipped 6507 empty bubbles
[2023-04-13 04:35:19] root: DEBUG: Skipped 260 bubbles with long branches
[2023-04-13 04:35:20] root: INFO: Alignment error rate: 0.159854
[2023-04-13 04:35:20] root: INFO: Correcting bubbles
[2023-04-13 04:56:16] root: ERROR: Command '['flye-modules', 'polisher', '--bubbles', '/home/fk8jybr/output/Flye/40-polishing/bubbles_1.fasta$
[2023-04-13 04:56:16] root: ERROR: Pipeline aborted
```

**Comment by mikolmogorov** [comment] 2023-04-19 15:04
Looks like duplicate of https://github.com/fenderglass/Flye/issues/584. If you are also getting parsing error exception, please continue the discussion in this thread.

Does your input fasta contains non-ACGT symbols? Could you try validating it with seqtk? To reproduce and fix the error, I would need a small sample of input that gives you the error - will you be able to come up with one?

Best,
Misha

**Comment by mikolmogorov** [comment] 2023-08-18 14:21
Closed due to inactivity.

**Closed as completed by mikolmogorov** 2023-08-18 14:21 UTC
Labels: duplicate, more info needed
