### ISSUE TITLE
ERROR: Missing from SAM header: contig_1

### ISSUE THREAD

**Issue by dvera** [fenderglass/ABruijn#60] opened 2018-10-23 09:59 UTC
Hello,

When I try to run fly, the sam header that is generated from minimap appears to lack sequence names. Only the @PG line is present in the file minimap.sam. This seems to be causing errors downstream:

```bash
root@flye:/tank# flye --pacbio-raw all.fastq --genome-size 3g --out-dir test1 --threads 28 --min-overlap 1000                                                                                                                             
[2018-10-18 00:21:05] INFO: Running Flye 2.3.6-release
[2018-10-18 00:21:05] INFO: Configuring run
[2018-10-18 00:25:15] INFO: Input genome size: 3000000000
[2018-10-18 00:25:15] INFO: Estimated coverage: 22
[2018-10-18 00:25:15] INFO: Reads N50/N90: 9711 / 2364
[2018-10-18 00:25:15] INFO: Selected k-mer size: 17
[2018-10-18 00:25:15] INFO: Assembling reads
[2018-10-18 00:25:15] INFO: Reading sequences
[2018-10-18 00:30:34] INFO: Generating solid k-mer index
[2018-10-18 00:30:55] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-18 00:38:10] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-18 01:12:22] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-18 02:28:41] INFO: Extending reads
[2018-10-18 02:34:11] INFO: Overlap-based coverage: 2
[2018-10-18 02:34:11] INFO: Median overlap divergence: 0.167175
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-20 09:18:04] INFO: Assembled 126800 draft contigs
[2018-10-20 09:20:35] INFO: Generating contig sequences
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2018-10-20 10:05:08] INFO: Running Minimap2
[2018-10-20 18:06:10] INFO: Computing consensus
[2018-10-20 18:11:47] ERROR: Missing from SAM header: contig_1
`

**Comment by mikolmogorov** [comment] 2018-10-23 21:55
Seems strange.. Can you post the outputs of ```head minimap.sam```, ```tail minimap.sam``` and ```head all.fastq```?

There were some updates in the version 2.3.6 that affected SAM processing. Could you also try version 2.3.5 and see if it is working for you? You can restart from last completed step (consensus, in your case) by adding ```--resume``` option (and running with the same output directory).

**Comment by dvera** [comment] 2018-10-24 12:42
first 10 lines of all.fastq

```bash
@m54015_180107_000439/4325718/5621_5807
AAGAGGCAGCAGCAGGACGAGGATCGACGGTGGAGACCGGAGGAAGCAGCAGCAGGACTGAGGACGAGGAGGAAGCAGAGCATGCAGGATGAGGGAGAGTATCGACGGAGGACGGAGGAGCAGCAGCAGGAGAGGACGAGACGACGAGAGACTGAGTAAAGCATACATACGAGGAGCGACCCGGAG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@m54015_180107_000439/4325906/130_434
TGGTCTGTGTGTGGCGAAAGAGTGGTAGGTGGGGGAGGGGGAAGGAGGGGGAGAGGAGGGGGATGTGTGGGGTAGGTGGTGAGAGATAGGGCGGGGATACGCGTGTAGGGGGAGGGGAAGCGGGGGGGCAAGGGTGAGCGGAAGGGGAGGTTGGGGGGTGGGAGGTGGTGTCGCCGACCCGTTCCTTTGTTTTTCCGTGGGCGGCTGGCACTTTTCCTATCTTGGCTTTCTTCCTCCCCCCAACCTCTTTCTCGTGCTTTTTTGTGTATTTCTTTCTCTTGCGTGTTCTTTTCTTTGGTTATCT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@m54015_180107_000439/4391093/978_1514
TCTCTGTCCCCACCCGGTCCCTCTGGTAGGGGGGGGGGTCTCTGCTTTCGTCTACATACAAGCACCTCGGCAGCCTCCCTGGCAAAATCACATTAACTAGCCCGTATTAGGACTCTCACTACTGCTCCCTATACTCATCCTCTGACACTCTCGTTACTCGCTGATCATCTTCGATACCTAACACATCTCCCATACTTCAACACACTCACCCCTTTTTTCTTTGTTTTTAGCAACAGCACTATCACAGCCGCTCAATATTATATATATACAGTTTTTTTCGGGACTGCTTTCCCTCTTTCTTTTCCTGTGATTACACATCACTCTTTACCGGTAATGAAATAGTCCGATGTTCATAAGAATTGTTTATAATGTATTGTAATTGAACATCATCCAATATACAAAATGCAGTGCAATGATCAGGAAAAAGAGTAGAACGCAATAATGGGAGTAGAAGTAACAATTACAAAACAAAGGGAAGGCGATGGGCTATTGCTGGTAACCTATTTGGAACTGATGGGTAATTTATGTTTTTTTTC
```

first two lines of minimap.sam
```bash
@PG	ID:minimap2	PN:minimap2	VN:2.12-r827	CL:minimap2 -a -Q -w5 -m100 -g10000 --max-chain-skip 25 -t 28 -Hk19 /tank/test1/0-assembly/draft_assembly.fasta all.fastq
m54015_180107_000439/11027101/721_902	4	*	0	0	*	*	0	0	TACTCTATACTACATACACACGACTGACTGACTGCATACTTTCATATATATATATTAGTTATTAGATATATAATATGATCTATGTGATCGATCGTTGTGT	*
```

The last lines are also reads. There are no header lines besides the PG line.

Do you think there is an issue with slashes in the read names?

Will try out the old version.

Thanks!

**Comment by dvera** [comment] 2018-10-24 18:19
2.3.5 also doesn't include sequence names in sam header with my input.

**Comment by mikolmogorov** [comment] 2018-10-24 18:36
Thank you. Looks like this is an expected behavior of minimap2 - https://github.com/lh3/minimap2/issues/37

Version 2.3.5 in fact does not rely on this tag - so it should go through. You can even allow 2.3.5 to finish with consensus and then restart 2.3.6 from the repeat analysis. Let me know if it works for you. In the mean time, I will work on a workaround to include into the upcoming releases.

**Comment by dvera** [comment] 2018-10-24 19:15
Thanks!

**Comment by mikolmogorov** [comment] 2018-11-01 18:33
Resolved in flye-devel now.

**Closed as completed by mikolmogorov** 2018-11-01 18:33 UTC
