### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by aasthakapoor95** [fenderglass/ABruijn#490] opened 2022-03-25 14:04 UTC
Hi,

I am facing the same issue

This is the output that i receive :

Running Minimap2
[2022-03-25 18:49:58] ERROR: Error running minimap2, terminating. See the alignment error log  for details: /home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/minimap.stderr
[2022-03-25 18:49:58] ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 /home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/chunks.fasta read_subsets_R30_filtlong1000_compiled/sample_01_deduplicated.fastq.gz -x map-ont -t 5 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/chunks.fasta -u - | flye-samtools sort -T /home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/sort_220325_184958 -O bam -@ 4 -l 1 -m 1G']' returned non-zero exit status 1.
[2022-03-25 18:49:58] ERROR: Pipeline aborted

I created more space, but observing the same error.

If i look into the miniasm.stdree file, it shows a different output for me:

[ERROR] failed to open file '/home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn'
[E::hts_open_format] Failed to open file _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/sort_220325_184958
samtools sort: can't open "_trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/sort_220325_184958": No such file or directory
[samfaipath] fail to read file /home/gmpl/gms/onp_analysis/3kpngenomes_g4_hacmod/pass/demultiplexed/barcode07/TRYCYCLER/3kpn.
[E::hts_open_format] Failed to open file _trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/chunks.fasta
samtools view: failed to open "_trycycler/assembly/flye/flye_filtlong1000_sample_01/10-consensus/chunks.fasta" for reading: No such file or directory

Someone can help me with this issue

**Comment by mikolmogorov** [comment] 2022-03-31 18:25
Duplicate of #489

**Closed as completed by mikolmogorov** 2022-03-31 18:25 UTC
