### ISSUE TITLE
Flye 2.7 died with Signals.SIGABRT: 6

### ISSUE THREAD

**Issue by lyrk50** [fenderglass/ABruijn#250] opened 2020-04-11 16:21 UTC
hello,
I run flye2.7 (flye --nano-raw allpass.fastq.gz --out-dir /helab/share/data/lyr_data/out_flye --genome-size 4.0g --trestle --threads 45) but it died with the following stdout:
[2020-04-05 10:25:13] DEBUG: Final graph contiain 82493 egdes
[2020-04-05 10:25:13] DEBUG: Extending contigs into repeats
[2020-04-05 10:26:49] DEBUG: Covered 24398 repetitive contigs
[2020-04-05 10:26:49] INFO: Generated 58136 contigs
[2020-04-05 10:26:50] DEBUG: Writing FASTA
[2020-04-05 10:28:06] DEBUG: Generating scaffold connections
[2020-04-05 10:28:07] INFO: Added 229 scaffold connections
[2020-04-05 10:28:07] DEBUG: Writing Dot
[2020-04-05 12:33:05] DEBUG: Writing FASTA
[2020-04-05 12:33:59] DEBUG: Writing Gfa
[2020-04-11 11:07:13] ERROR: Caught unhandled exception: std::bad_alloc
[2020-04-11 11:07:13] ERROR:    flye-modules(_Z16exceptionHandlerv+0xda) [0x55b145ffd2ea]
[2020-04-11 11:07:13] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6) [0x7f13943ecae6]
[2020-04-11 11:07:13] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b21) [0x7f13943ecb21]
[2020-04-11 11:07:13] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d54) [0x7f13943ecd54]
[2020-04-11 11:07:13] ERROR:    /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x932dc) [0x7f13943ed2dc]
[2020-04-11 11:07:13] ERROR:    flye-modules(+0xebac0) [0x55b1460abac0]
[2020-04-11 11:07:13] ERROR:    flye-modules(_ZN15OutputGenerator9outputGfaERKSt6vectorI15UnbranchingPathSaIS1_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xae1) [0x55b1460ac5e1]
[2020-04-11 11:07:13] ERROR:    flye-modules(_Z14contigger_mainiPPc+0x1da4) [0x55b1460d0924]
[2020-04-11 11:07:13] ERROR:    flye-modules(main+0x148) [0x55b145ff71f8]
[2020-04-11 11:07:13] ERROR:    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f13937b7b97]
[2020-04-11 11:08:04] root: ERROR: Command '['flye-modules', 'contigger', '--graph-edges', '/he_lab/share/data/user/lvyanrong/out_flye/21-trestle/repeat_graph_edges.fasta', '--reads', 'allpass.fastq.gz', '--out-dir', '/he_lab/share/data/user/lvyanrong/out_flye/30-contigger', '--config', '/he_lab/share/data/local/Flye-2.7/flye/config/bin_cfg/asm_raw_reads.cfg', '--repeat-graph', '/he_lab/share/data/user/lvyanrong/out_flye/21-trestle/repeat_graph_dump', '--graph-aln', '/he_lab/share/data/user/lvyanrong/out_flye/20-repeat/read_alignment_dump', '--log', '/he_lab/share/data/user/lvyanrong/out_flye/flye.log', '--threads', '50', '--min-ovlp', '5000', '--kmer', '17']' died with <Signals.SIGABRT: 6>.
[2020-04-11 11:08:04] root: ERROR: Pipeline aborted
I wonder if the output contigs.fasta in 30-contigger file is complete and can be used for further analysis. Do you think I can avoid this bug if I `--resume-from contigger`?
Thanks,
lynn

**Comment by mikolmogorov** [comment] 2020-04-14 18:06
Duplicate of #234.

**Comment by mikolmogorov** [comment] 2020-04-14 18:06
It is likely related to #234, please check the thread for the solution.

**Closed as completed by mikolmogorov** 2020-04-14 18:06 UTC
