### ISSUE TITLE
No disjointigs were assembled - please check if the read type and genome size parameters are correct

### ISSUE THREAD

**Issue by lqhungpt** [fenderglass/ABruijn#708] opened 2024-06-05 04:40 UTC
Hi Admin,
I tried to use Flye to assemble Nanopore raw reads with super-accurate base calling. The N50 length for my raw read was under 1kb. However, although I input the correct genome size of my virus, I have issues like the one below. Can you show me the main problem? I tried with SPAdes assembly with the same reads, it gave me a contig with around 15kb.

[2024-06-04 23:37:00] INFO: Starting Flye 2.9.4-b1799
[2024-06-04 23:37:00] INFO: >>>STAGE: configure
[2024-06-04 23:37:00] INFO: Configuring run
[2024-06-04 23:37:00] INFO: Total read length: 5573764
[2024-06-04 23:37:00] INFO: Input genome size: 15000
[2024-06-04 23:37:00] INFO: Estimated coverage: 371
[2024-06-04 23:37:00] INFO: Reads N50/N90: 563 / 261
[2024-06-04 23:37:00] INFO: Minimum overlap set to 1000
[2024-06-04 23:37:00] INFO: Using longest 50x reads for contig assembly
[2024-06-04 23:37:00] INFO: >>>STAGE: assembly
[2024-06-04 23:37:00] INFO: Assembling disjointigs
[2024-06-04 23:37:00] INFO: Reading sequences
[2024-06-04 23:37:00] INFO: Building minimizer index
[2024-06-04 23:37:00] INFO: Pre-calculating index storage
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2024-06-04 23:37:00] INFO: Filling index
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2024-06-04 23:37:05] INFO: Extending reads
[2024-06-04 23:37:07] INFO: Overlap-based coverage: 21
[2024-06-04 23:37:07] INFO: Median overlap divergence: 0.0506971
0% 100% 
[2024-06-04 23:37:09] INFO: Assembled 0 disjointigs
[2024-06-04 23:37:09] INFO: Generating sequence
[2024-06-04 23:37:09] INFO: Filtering contained disjointigs
[2024-06-04 23:37:09] INFO: Contained seqs: 0
[2024-06-04 23:37:09] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2024-06-04 23:37:09] ERROR: Pipeline aborted

**Comment by mikolmogorov** [comment] 2024-06-10 21:40
Duplicate of https://github.com/fenderglass/Flye/issues/128. Please see if anything from that thread applies. If it does not resolve your issue, please follow up in the original thread.

**Closed as completed by mikolmogorov** 2024-06-10 21:40 UTC
Labels: duplicate
