### ISSUE TITLE
assembly error No disjointigs were assembled

### ISSUE THREAD

**Issue by isabelluo** [fenderglass/ABruijn#704] opened 2024-05-21 18:59 UTC
Hi I was running flye on Geneious and the following are the log files generated 
ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct

Failed to run: /Users/luoyizhen/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/bin/flye --nano-raw input_0_Unpaired.fastq --threads 8 --genome-size 5m --iterations 1 -t 10 --out-dir out, exit code: 1

Flye reported the following errors:
[2024-05-21 12:42:00] INFO: Starting Flye 2.9.1-b1780
[2024-05-21 12:42:00] INFO: >>>STAGE: configure
[2024-05-21 12:42:00] INFO: Configuring run
[2024-05-21 12:42:02] INFO: Total read length: 196211018
[2024-05-21 12:42:02] INFO: Input genome size: 5000000
[2024-05-21 12:42:02] INFO: Estimated coverage: 39
[2024-05-21 12:42:02] INFO: Reads N50/N90: 10205 / 2801
[2024-05-21 12:42:02] INFO: Minimum overlap set to 3000
[2024-05-21 12:42:02] INFO: >>>STAGE: assembly
[2024-05-21 12:42:02] INFO: Assembling disjointigs
[2024-05-21 12:42:02] INFO: Reading sequences
[2024-05-21 12:42:09] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2024-05-21 12:45:23] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2024-05-21 12:47:55] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2024-05-21 12:58:34] INFO: Extending reads
[2024-05-21 13:20:29] INFO: Overlap-based coverage: 3466
[2024-05-21 13:20:29] INFO: Median overlap divergence: 0.0566537
0% 100%
[2024-05-21 14:33:46] INFO: Assembled 0 disjointigs
[2024-05-21 14:33:46] INFO: Generating sequence
[2024-05-21 14:33:46] INFO: Filtering contained disjointigs
[2024-05-21 14:33:46] INFO: Contained seqs: 0
[2024-05-21 14:33:47] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2024-05-21 14:33:47] ERROR: Pipeline aborted

What could the problem be?

**Comment by mikolmogorov** [comment] 2024-05-22 20:03
Duplicate of https://github.com/fenderglass/Flye/issues/128. Please check this thread and see if anything applies. If not, feel free to continue in the original thread.

**Closed as completed by mikolmogorov** 2024-05-22 20:03 UTC
Labels: duplicate
