### ISSUE TITLE
 No disjointigs were assembled - please check if the read type and genome size parameters are correct

### ISSUE THREAD

**Issue by anilchauhanhp9** [fenderglass/ABruijn#383] opened 2021-04-29 14:35 UTC
Hi,
i ran the program on nanopore raw reads consisting of bacterial DNA reads with following command
**flye --nano-raw /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Srijana/nanopore_data/Sri_whole_genome_sikkim_25032021/fastq_pass/barcode12/barcode12.fastq.gz -g 5m -o //media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed/Srijana/nanopore_data/Sri_whole_genome_sikkim_25032021/analysis/Assembly/barcode12 -t 20**
The program gave me the following error
 **No disjointigs were assembled - please check if the read type and genome size parameters are correct**
the log file is attached
[flye.log](https://github.com/fenderglass/Flye/files/6399438/flye.log)
please help

**Comment by mikolmogorov** [comment] 2021-04-29 20:47
Duplicate of #128. Please check if anything in that discussion applies. If nothing helps, please follow up with more details about your dataset. Did other assemblers worked for this dataset?

**Closed as completed by mikolmogorov** 2021-04-29 20:47 UTC
Labels: duplicate
