### ISSUE TITLE
Flye 2.6 crashes on macOS Mojave with Python 3.8

### ISSUE THREAD

**Issue by MacVectorKevin** [fenderglass/ABruijn#180] opened 2019-10-29 21:05 UTC
Hi,

As per the title I'm seeing what appear to be some threading issues with Flye2.6 and Python3 as shown in the attached text document. All appears to run OK until the consensus calculation step then it appears a second job is started in a non-main thread, the entire assembly procedure repeats until the consensus calculation step then a multiprocessing runtime error occurs.

With Flye 2.5, or with Python 2.7, all appears to complete normally.

Kevin

[FlyeCrashOutput.txt](https://github.com/fenderglass/Flye/files/3785778/FlyeCrashOutput.txt)

**Comment by mikolmogorov** [comment] 2019-10-30 17:24
Seems odd, `freeze_support()` seems to be related to generating frozen executables for Windows. Did you install Flye from source (bioconda doesn't support Py 3.8 yet)? Does Python 3.7 work?

Can anybody else confirm crash on Python 3.8?

**Comment by MacVectorKevin** [comment] 2019-10-30 17:46
I built Flye from source on a different Mac running macOS Catalina. It has Anaconda with Python 3.6, but "python -V" indicates python 2.7 is the default and that was used to build the Flye binaries which were then transferred to the second Mac. Whereas Flye ran fine on the first Mac, it complained about needing Python3 on the second Mac so I downloaded and installed the latest from python.org. 

I think the message about Windows frozen executables is a bit of a red herring - it seems to be a generic error message as the most likely cause, but its actually just detecting some kind of nested multi-threading issue.

Kevin

**Comment by mikolmogorov** [comment] 2019-10-30 22:06
I see. Please make sure that you are using the same version of Python and environment for `setup.py` and running the pipeline. It could be tricky for machines with multiple interpreter versions - bioconda package is the recommended way to handle the environment issues in this case. I think this error was likely caused by the environment inconsistency.

Since you got Flye working, I am closing the issue (you can use the bioconda package for flye 2.6). Python 3.8 was just released, and I am not planning to work on 3.8 support until it is adopted as one of the build environments for Bioconda.

**Closed as completed by mikolmogorov** 2019-10-30 22:06 UTC
Labels: more info needed
